"""
Validates the demo content and writes supabase/seed/0002_demo_content.sql and content/sample_import.csv.

Run:  python3 content/build_seed.py
Checks: topic exists, four distinct non-empty options, answer is A–D, no duplicate questions,
explanation present, and blueprint coverage (enough questions per subject for a full mock).
"""
import csv, re, sys
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "content"))
from demo_questions import QUESTIONS  # noqa: E402
from revision_notes import NOTES  # noqa: E402

BLUEPRINT = {"english": 15, "reasoning": 15, "quant": 15, "ga-aviation": 15,
             "physics": 24, "mathematics": 24, "management": 12}
GA_SPLIT = {"Aviation": 11, "Static GK": 4}

# ---- read topic slugs (and GA groups) from the syllabus seed ----
syllabus = (ROOT / "supabase/seed/0001_syllabus.sql").read_text()
topics = {}
for subj, slug, grp in re.findall(r"\('([a-z-]+)','([a-z0-9-]+)','[^']*(?:''[^']*)*','([^']*)',\d+\)", syllabus):
    topics[(subj, slug)] = grp

errors = []
seen = set()
for i, q in enumerate(QUESTIONS, 1):
    where = f"#{i} ({q.subject}/{q.topic})"
    if (q.subject, q.topic) not in topics:
        errors.append(f"{where}: unknown topic")
    if q.difficulty not in ("easy", "moderate", "exam", "challenging"):
        errors.append(f"{where}: bad difficulty {q.difficulty}")
    if len(q.options) != 4 or any(not o.strip() for o in q.options):
        errors.append(f"{where}: needs 4 non-empty options")
    if len(set(o.strip() for o in q.options)) != 4:
        errors.append(f"{where}: options not distinct")
    if q.answer not in "ABCD" or len(q.answer) != 1:
        errors.append(f"{where}: bad answer {q.answer}")
    if not q.explanation.strip():
        errors.append(f"{where}: missing explanation")
    key = re.sub(r"\s+", " ", q.text.strip().lower())
    if key in seen:
        errors.append(f"{where}: duplicate question text")
    seen.add(key)

by_subject = Counter(q.subject for q in QUESTIONS)
for s, need in BLUEPRINT.items():
    if by_subject[s] < need:
        errors.append(f"{s}: only {by_subject[s]} questions, a full mock needs {need}")
ga_groups = Counter(topics.get((q.subject, q.topic)) for q in QUESTIONS if q.subject == "ga-aviation")
for g, need in GA_SPLIT.items():
    if ga_groups[g] < need:
        errors.append(f"GA group {g}: only {ga_groups[g]}, needs {need}")

if errors:
    print("VALIDATION FAILED:\n  " + "\n  ".join(errors))
    sys.exit(1)

# ---- spread correct answers evenly over A–D (deterministic) ----
# Options that are themselves labels ("A".."D", "Only I follows"...) keep their natural order.
import random
rng = random.Random(2026)
for i, q in enumerate(QUESTIONS):
    if q.options == ["A", "B", "C", "D"] or q.options[0].startswith("Only "):
        continue
    target = "ABCD"[i % 4]
    correct_text = q.options[ord(q.answer) - 65]
    others = [o for o in q.options if o != correct_text]
    rng.shuffle(others)
    t = ord(target) - 65
    q.options = others[:t] + [correct_text] + others[t:]
    q.answer = target


def sql(s):
    return "'" + s.replace("'", "''") + "'"


out = ["-- GENERATED by content/build_seed.py — do not edit by hand.",
       "-- Original demo questions (source = 'demo'), written for this platform. Not official AAI questions.",
       ""]
out.append("insert into questions (subject_id, topic_id, question_text, option_a, option_b, option_c, option_d,")
out.append("  correct_option, explanation, concept, difficulty, source, is_verified, tags)")
out.append("select s.id, t.id, v.q, v.a, v.b, v.c, v.d, v.ans, v.expl, v.concept, v.diff::difficulty_level,")
out.append("  'demo', true, v.tags::text[]")
out.append("from (values")
rows = []
for q in QUESTIONS:
    a, b, c, d = q.options
    rows.append("  (" + ", ".join([sql(q.subject), sql(q.topic), sql(q.text), sql(a), sql(b), sql(c), sql(d),
                                  sql(q.answer), sql(q.explanation), sql(q.concept), sql(q.difficulty),
                                  sql("{" + ",".join(q.tags) + "}")]) + ")")
out.append(",\n".join(rows))
out.append(") as v(subj, topic, q, a, b, c, d, ans, expl, concept, diff, tags)")
out.append("join subjects s on s.slug = v.subj join topics t on t.subject_id = s.id and t.slug = v.topic;")
out.append("")

out.append("insert into revision_notes (subject_id, category, title, body, sort_order)")
out.append("select s.id, v.cat, v.title, v.body, v.ord from (values")
out.append(",\n".join("  (" + ", ".join([sql(sub), sql(cat), sql(title), sql(body.strip()), str(i)]) + ")"
                      for i, (sub, cat, title, body) in enumerate(NOTES, 1)))
out.append(") as v(subj, cat, title, body, ord) join subjects s on s.slug = v.subj;")
out.append("")

MOCKS = [
    (1, "Foundation", '{"easy":3,"moderate":2,"exam":1,"challenging":0.2}'),
    (2, "Foundation", '{"easy":3,"moderate":2,"exam":1,"challenging":0.2}'),
    (3, "Standard", '{"easy":1,"moderate":3,"exam":2,"challenging":0.5}'),
    (4, "Standard", '{"easy":1,"moderate":3,"exam":2,"challenging":0.5}'),
    (5, "Standard", '{"easy":1,"moderate":3,"exam":2,"challenging":0.5}'),
    (6, "Exam Level", '{"easy":0.5,"moderate":1.5,"exam":3,"challenging":1}'),
    (7, "Exam Level", '{"easy":0.5,"moderate":1.5,"exam":3,"challenging":1}'),
    (8, "Advanced Practice", '{"easy":0.2,"moderate":1,"exam":2,"challenging":3}'),
    (9, "Exam Simulation", '{"easy":1,"moderate":2,"exam":3,"challenging":1}'),
    (10, "Final Simulation", '{"easy":1,"moderate":2,"exam":3,"challenging":1}'),
]
out.append("insert into tests (kind, title, series_label, series_number, description, config, is_published) values")
mrows = []
for n, label, w in MOCKS:
    kind = "exam_simulation" if n >= 9 else "full_mock"
    desc = ("Strict exam conditions: 120 questions, 120 minutes, no explanations until you submit, auto-submit at 00:00."
            if kind == "exam_simulation" else
            f"{label} difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.")
    mrows.append(f"  ('{kind}', 'Mock {n:02d} — {label}', '{label}', {n}, {sql(desc)}, '{{\"weights\":{w}}}', true)")
out.append(",\n".join(mrows) + ";")
out.append("")

(ROOT / "supabase/seed/0002_demo_content.sql").write_text("\n".join(out))

# CSV sample for the admin importer (same headers the importer expects)
with open(ROOT / "content/sample_import.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["question", "optionA", "optionB", "optionC", "optionD", "correctAnswer", "explanation",
                "subject", "topic", "difficulty", "source", "year"])
    w.writerow(["(Example) A body moving in a circle at constant speed has:", "Zero acceleration",
                "Acceleration towards the centre", "Acceleration along the tangent", "Constant velocity", "B",
                "Direction changes continuously, so there is centripetal acceleration towards the centre.",
                "physics", "motion", "easy", "original", ""])

print(f"OK: {len(QUESTIONS)} questions, {len(NOTES)} note sheets, {len(MOCKS)} mocks")
print("Per subject:", dict(by_subject))
print("GA groups:", dict(ga_groups))
print("Difficulty:", dict(Counter(q.difficulty for q in QUESTIONS)))
print("Answer letters:", dict(Counter(q.answer for q in QUESTIONS)))
