"""
Original demo question bank for the AAI JE (Operations) prep platform.

Every question here was written for this platform (source = 'demo'). None is copied from any
book or official paper. Difficulty and topic mix follow docs/reference-analysis.md.

Format: Q(subject_slug, topic_slug, difficulty, question, [A, B, C, D], answer_letter, explanation, concept)
difficulty: easy | moderate | exam | challenging
"""
from dataclasses import dataclass, field


@dataclass
class Q:
    subject: str
    topic: str
    difficulty: str
    text: str
    options: list
    answer: str
    explanation: str
    concept: str = ""
    tags: list = field(default_factory=list)


QUESTIONS = [
    # ======================= ENGLISH =======================
    Q("english", "synonyms", "easy", "Choose the word most similar in meaning to CANDID.",
      ["Frank", "Secretive", "Careless", "Rude"], "A",
      "Candid means open and honest in speech, i.e. frank.", "Synonyms"),
    Q("english", "synonyms", "moderate", "Choose the word most similar in meaning to METICULOUS.",
      ["Careless", "Hasty", "Painstaking", "Indifferent"], "C",
      "Meticulous means showing great attention to detail — painstaking.", "Synonyms"),
    Q("english", "antonyms", "easy", "Choose the word opposite in meaning to SCARCE.",
      ["Rare", "Abundant", "Meagre", "Insufficient"], "B",
      "Scarce means in short supply; its opposite is abundant.", "Antonyms"),
    Q("english", "antonyms", "moderate", "Choose the word opposite in meaning to EPHEMERAL.",
      ["Transient", "Fleeting", "Brief", "Permanent"], "D",
      "Ephemeral means lasting a very short time; the opposite is permanent. The other three are synonyms.", "Antonyms"),
    Q("english", "antonyms", "easy", "Choose the word opposite in meaning to RELUCTANT.",
      ["Unwilling", "Eager", "Hesitant", "Averse"], "B",
      "Reluctant means unwilling; its opposite is eager.", "Antonyms"),
    Q("english", "idioms-phrases", "easy", "Choose the meaning of the idiom: to burn the midnight oil",
      ["To waste resources", "To work or study late into the night", "To start a quarrel", "To celebrate a success"], "B",
      "To burn the midnight oil is to stay up late working or studying.", "Idioms"),
    Q("english", "idioms-phrases", "moderate", "Choose the meaning of the idiom: a blessing in disguise",
      ["An obvious advantage", "A hidden danger",
       "Something that seems bad at first but turns out to be good", "An unexpected gift from a stranger"], "C",
      "A blessing in disguise is an apparent misfortune that later proves beneficial.", "Idioms"),
    Q("english", "one-word-substitution", "easy", "One word for: a person who can speak two languages fluently.",
      ["Polyglot", "Bilingual", "Linguist", "Interpreter"], "B",
      "Bilingual = fluent in two languages. A polyglot knows many languages.", "One-word substitution"),
    Q("english", "one-word-substitution", "moderate", "One word for: a large shed in which aircraft are housed and repaired.",
      ["Hanger", "Garage", "Hangar", "Depot"], "C",
      "Hangar (with -ar) is the aircraft shed. Hanger (with -er) is something you hang clothes on.", "One-word substitution"),
    Q("english", "spelling", "moderate", "Choose the correctly spelt word.",
      ["Accomodation", "Accommodation", "Acommodation", "Accommadation"], "B",
      "Accommodation has double c and double m.", "Spelling"),
    Q("english", "articles", "easy", "Fill in the blank: He is ___ honest man.",
      ["a", "an", "the", "no article"], "B",
      "'Honest' begins with a vowel sound (the h is silent), so 'an' is used.", "Articles"),
    Q("english", "prepositions", "moderate", "Fill in the blank: The flight was delayed ___ bad weather.",
      ["because", "owing to", "since", "despite"], "B",
      "'Owing to' is a preposition meaning 'because of'. 'Because' alone needs 'of'; 'despite' reverses the meaning.", "Prepositions"),
    Q("english", "subject-verb-agreement", "exam",
      "Fill in the blank: Neither the pilot nor the crew members ___ aware of the change in schedule.",
      ["was", "is", "has been", "were"], "D",
      "With neither…nor, the verb agrees with the nearer subject. 'Crew members' is plural, so 'were'.", "Subject-verb agreement"),
    Q("english", "tenses", "moderate", "Fill in the blank: By the time we reached the airport, the flight ___.",
      ["left", "had left", "has left", "was leaving"], "B",
      "The earlier of two past actions takes the past perfect: had left.", "Past perfect tense"),
    Q("english", "active-passive", "moderate",
      "Choose the passive form: The controller cleared the aircraft for take-off.",
      ["The aircraft was cleared for take-off by the controller.",
       "The aircraft is cleared for take-off by the controller.",
       "The aircraft had been cleared for take-off by the controller.",
       "The aircraft was being cleared for take-off by the controller."], "A",
      "Simple past active (cleared) becomes was + past participle (was cleared).", "Active and passive voice"),
    Q("english", "direct-indirect", "moderate", "Choose the indirect form: He said, \"I am tired.\"",
      ["He said that I am tired.", "He said that he was tired.", "He said that he is tired.", "He told that he was tired."], "B",
      "Reporting verb in past: 'am' becomes 'was' and 'I' becomes 'he'. 'Told' needs an object.", "Direct and indirect speech"),
    Q("english", "error-detection", "exam",
      "Find the part with an error: One of my friends (A) / are working (B) / at the Delhi airport. (C) / No error (D)",
      ["A", "B", "C", "D"], "B",
      "The subject is 'One', which is singular, so it should be 'is working'.", "Error detection"),
    Q("english", "sentence-improvement", "exam",
      "Improve the underlined part: If I was a pilot, I would fly across the world. (underlined: If I was)",
      ["If I were", "If I am", "If I had been", "No improvement"], "A",
      "Imaginary or hypothetical conditions take the subjunctive 'were' for all persons.", "Subjunctive mood"),
    Q("english", "fill-blanks", "moderate",
      "Fill in the blank: The new terminal was designed to ___ ten million passengers a year.",
      ["accumulate", "accommodate", "assimilate", "alleviate"], "B",
      "Accommodate = provide space for. The others do not fit the sense.", "Vocabulary in context"),
    Q("english", "fill-blanks", "easy", "Fill in the blank: Safety is the ___ priority of every airline.",
      ["paramount", "paranoid", "parallel", "partial"], "A",
      "Paramount means of supreme importance.", "Vocabulary in context"),
    Q("english", "vocabulary", "easy", "Choose the correct word: The medicine had a good ___ on him.",
      ["affect", "effort", "effect", "afect"], "C",
      "'Effect' (noun) is the result; 'affect' is usually a verb.", "Confusable words"),
    Q("english", "para-jumbles", "exam",
      "Passengers first arrive at the terminal. Arrange the rest in order:\n"
      "P: They then collect their boarding passes at the check-in counter.\n"
      "Q: After security screening, they proceed to the boarding gate.\n"
      "R: Checked baggage is handed over at the same counter.\n"
      "S: Finally, they board the aircraft when the gate opens.",
      ["PRQS", "RPQS", "PQRS", "QPRS"], "A",
      "'The same counter' in R refers back to P, so P–R; security (Q) comes before boarding (S).", "Para jumbles"),
    Q("english", "reading-comprehension", "moderate",
      "Read the passage and answer.\n\"Radar allows air traffic controllers to see aircraft even in cloud or at night. "
      "Primary radar detects signals reflected from the aircraft's body, while secondary radar relies on a transponder "
      "on board, which replies with the aircraft's identity and altitude.\"\n"
      "According to the passage, secondary radar depends on:",
      ["Reflection from the aircraft's body", "Clear weather", "A transponder on the aircraft", "Daylight"], "C",
      "The passage states that secondary radar relies on the on-board transponder.", "Reading comprehension"),

    # ======================= REASONING =======================
    Q("reasoning", "number-series", "easy", "Find the next term: 3, 6, 12, 24, ?",
      ["36", "48", "42", "30"], "B", "Each term is double the previous one: 24 × 2 = 48.", "Geometric series"),
    Q("reasoning", "number-series", "moderate", "Find the next term: 2, 6, 12, 20, 30, ?",
      ["40", "44", "42", "36"], "C", "Differences are 4, 6, 8, 10, so the next is 12: 30 + 12 = 42.", "Difference series"),
    Q("reasoning", "number-series", "easy", "Find the next term: 1, 8, 27, 64, ?",
      ["100", "81", "216", "125"], "D", "These are cubes 1³, 2³, 3³, 4³; next is 5³ = 125.", "Cube series"),
    Q("reasoning", "alphabet-series", "moderate", "Find the next term: A, C, F, J, O, ?",
      ["T", "U", "V", "S"], "B", "Gaps are +2, +3, +4, +5, then +6. O (15) + 6 = U (21).", "Alphabet series"),
    Q("reasoning", "letter-number-symbol-series", "easy", "Find the next term: AZ, BY, CX, ?",
      ["DV", "EW", "DW", "DX"], "C", "First letters go forward (A, B, C, D); second letters go backward (Z, Y, X, W).", "Letter pairs"),
    Q("reasoning", "coding-decoding", "moderate",
      "If AIRPORT is coded as BJSQPSU, how is RUNWAY coded?",
      ["SVOXAZ", "SVOXBZ", "TVOXBZ", "SVPXBZ"], "B",
      "Each letter moves one step forward: R→S, U→V, N→O, W→X, A→B, Y→Z.", "Letter shift coding"),
    Q("reasoning", "coding-decoding", "easy", "If FLIGHT is written as THGILF, how is PILOT written?",
      ["TOLPI", "TOLIP", "OTLIP", "TPLOI"], "B", "The word is simply reversed: PILOT → TOLIP.", "Reverse coding"),
    Q("reasoning", "blood-relations", "moderate",
      "Pointing to a man, Riya said, \"He is the son of my grandfather's only son.\" How is the man related to Riya?",
      ["Cousin", "Uncle", "Brother", "Father"], "C",
      "Her grandfather's only son is her father; her father's son is her brother.", "Blood relations"),
    Q("reasoning", "blood-relations", "exam",
      "A is B's sister. C is B's mother. D is C's father. How is A related to D?",
      ["Daughter", "Granddaughter", "Grandmother", "Niece"], "B",
      "A is C's daughter, and C is D's child, so A (female) is D's granddaughter.", "Blood relations"),
    Q("reasoning", "direction-sense", "moderate",
      "A man walks 4 km north, turns right and walks 3 km, then turns right again and walks 4 km. Where is he from the start?",
      ["3 km West", "5 km North-East", "7 km East", "3 km East"], "D",
      "North 4, east 3, south 4: the north and south cancel, leaving 3 km east.", "Direction sense"),
    Q("reasoning", "direction-sense", "easy",
      "Rahul faces east. He turns 90° clockwise and then 180° anticlockwise. Which direction is he facing now?",
      ["North", "South", "West", "East"], "A", "East → (90° clockwise) South → (180°) North.", "Turns"),
    Q("reasoning", "syllogism", "exam",
      "Statements: All pilots are officers. Some officers are engineers.\n"
      "Conclusions: I. Some pilots are engineers. II. Some engineers are officers.",
      ["Only I follows", "Only II follows", "Both follow", "Neither follows"], "B",
      "II is the conversion of 'some officers are engineers'. I is not certain — the engineer-officers may not be pilots.", "Syllogism"),
    Q("reasoning", "syllogism", "moderate",
      "Statements: All runways are paved. No paved surface is grass.\n"
      "Conclusions: I. No runway is grass. II. Some grass is runway.",
      ["Only I follows", "Only II follows", "Both follow", "Neither follows"], "A",
      "All runways lie inside 'paved', which has no overlap with grass, so no runway is grass; II contradicts I.", "Syllogism"),
    Q("reasoning", "analogy", "easy", "Pilot : Cockpit :: Chef : ?",
      ["Menu", "Kitchen", "Restaurant", "Waiter"], "B", "A pilot works in the cockpit; a chef works in the kitchen.", "Workplace analogy"),
    Q("reasoning", "odd-one-out", "moderate", "Find the odd one out: 27, 64, 125, 144",
      ["27", "64", "125", "144"], "D", "27, 64 and 125 are cubes; 144 is a square (12²), not a cube.", "Number classification"),
    Q("reasoning", "classification", "easy", "Find the odd one out: Mercury, Venus, Moon, Mars",
      ["Mercury", "Venus", "Moon", "Mars"], "C", "The Moon is a natural satellite; the others are planets.", "Classification"),
    Q("reasoning", "ranking", "easy", "In a row of 40 students, Anil is 12th from the left. What is his position from the right?",
      ["28th", "30th", "29th", "27th"], "C", "Position from right = 40 − 12 + 1 = 29.", "Ranking"),
    Q("reasoning", "seating-arrangement", "exam",
      "P, Q, R, S and T sit in a row facing north. R sits at the extreme left end and S at the extreme right end. "
      "Q sits immediately to the right of P. T sits immediately to the left of S. Who sits in the middle?",
      ["P", "T", "R", "Q"], "D",
      "Positions: R(1), S(5), T(4). P and Q take 2 and 3 with Q to the right of P, so the order is R P Q T S.", "Linear arrangement"),
    Q("reasoning", "mathematical-operations", "moderate",
      "If '+' means '×', '−' means '+', '×' means '÷' and '÷' means '−', find the value of 8 + 3 − 12 × 4 ÷ 5.",
      ["24", "22", "19", "26"], "B",
      "The expression becomes 8 × 3 + 12 ÷ 4 − 5 = 24 + 3 − 5 = 22.", "Symbol substitution"),
    Q("reasoning", "inequalities", "moderate",
      "Statements: P > Q ≥ R = S < T. Conclusions: I. P > S  II. T > R",
      ["Only I follows", "Only II follows", "Both follow", "Neither follows"], "C",
      "P > Q ≥ R = S gives P > S. T > S and S = R give T > R. Both follow.", "Inequalities"),
    Q("reasoning", "statement-conclusions", "moderate",
      "Statement: All passengers must complete security screening before boarding.\n"
      "Conclusions: I. Screening is required for boarding. II. Every screened passenger will definitely board.",
      ["Only I follows", "Only II follows", "Both follow", "Neither follows"], "A",
      "Screening is a necessary condition, not a guarantee of boarding.", "Statement and conclusions"),
    Q("reasoning", "mirror-water-images", "exam", "A clock shows 3:15. What time does its mirror image show?",
      ["9:45", "8:45", "8:15", "9:15"], "B", "Mirror time = 11:60 − 3:15 = 8:45.", "Clock mirror image"),
    Q("reasoning", "logical-word-order", "easy",
      "Arrange in a logical order: 1. Landing 2. Take-off 3. Boarding 4. Check-in 5. Taxiing",
      ["3, 4, 5, 2, 1", "4, 3, 2, 5, 1", "4, 3, 5, 2, 1", "4, 5, 3, 2, 1"], "C",
      "Check-in → boarding → taxiing → take-off → landing.", "Logical sequence"),

    # ======================= QUANTITATIVE APTITUDE =======================
    Q("quant", "percentage", "easy", "What is 25% of 480?", ["110", "120", "125", "96"], "B",
      "25% = 1/4, and 480 ÷ 4 = 120.", "Percentage"),
    Q("quant", "percentage", "moderate", "A price is increased by 20% and then decreased by 20%. The net change is:",
      ["No change", "2% decrease", "4% increase", "4% decrease"], "D",
      "Net = 20 − 20 − (20 × 20)/100 = −4%, i.e. a 4% decrease.", "Successive percentage change"),
    Q("quant", "profit-loss", "easy", "An article bought for ₹800 is sold for ₹920. Find the profit percentage.",
      ["12%", "15%", "18%", "20%"], "B", "Profit = 120; 120/800 × 100 = 15%.", "Profit percentage"),
    Q("quant", "discount", "moderate", "The marked price is ₹1,500. Successive discounts of 10% and 20% are given. Find the selling price.",
      ["₹1,050", "₹1,200", "₹1,080", "₹1,100"], "C", "1500 × 0.9 × 0.8 = ₹1,080.", "Successive discounts"),
    Q("quant", "simple-interest", "easy", "Find the simple interest on ₹5,000 at 8% per annum for 3 years.",
      ["₹1,200", "₹1,250", "₹1,100", "₹1,300"], "A", "SI = PRT/100 = 5000 × 8 × 3 / 100 = ₹1,200.", "Simple interest"),
    Q("quant", "compound-interest", "moderate", "Find the compound interest on ₹10,000 at 10% per annum for 2 years, compounded annually.",
      ["₹2,000", "₹2,200", "₹2,010", "₹2,100"], "D", "Amount = 10000 × 1.1² = 12,100; CI = ₹2,100.", "Compound interest"),
    Q("quant", "ratio-proportion", "easy", "₹1,200 is divided in the ratio 3 : 5. Find the larger share.",
      ["₹450", "₹700", "₹750", "₹800"], "C", "Larger share = 5/8 × 1200 = ₹750.", "Ratio division"),
    Q("quant", "average", "moderate",
      "The average of 5 numbers is 42. When one number is removed, the average of the rest is 40. Find the number removed.",
      ["48", "50", "52", "46"], "B", "Total 5 × 42 = 210; remaining 4 × 40 = 160; removed = 50.", "Average"),
    Q("quant", "time-work", "moderate", "A can finish a job in 12 days and B in 18 days. Working together, how long will they take?",
      ["7.2 days", "7.5 days", "6 days", "8 days"], "A", "1/12 + 1/18 = 5/36 per day, so 36/5 = 7.2 days.", "Combined work"),
    Q("quant", "pipes-cisterns", "moderate",
      "A pipe fills a tank in 6 hours and another empties it in 9 hours. If both are opened together, the tank fills in:",
      ["15 hours", "12 hours", "18 hours", "3 hours"], "C", "Net rate = 1/6 − 1/9 = 1/18, so 18 hours.", "Pipes and cisterns"),
    Q("quant", "time-speed-distance", "easy", "Express 72 km/h in m/s.",
      ["18 m/s", "20 m/s", "25 m/s", "22 m/s"], "B", "72 × 5/18 = 20 m/s.", "Unit conversion"),
    Q("quant", "time-speed-distance", "moderate", "A 150 m long train runs at 54 km/h. How long does it take to cross a pole?",
      ["8 s", "12 s", "15 s", "10 s"], "D", "54 km/h = 15 m/s; time = 150/15 = 10 s.", "Train problems"),
    Q("quant", "boats-streams", "moderate", "A boat's downstream speed is 18 km/h and upstream speed is 12 km/h. Find the speed of the stream.",
      ["3 km/h", "6 km/h", "15 km/h", "2 km/h"], "A", "Stream = (18 − 12)/2 = 3 km/h.", "Boats and streams"),
    Q("quant", "number-system", "easy", "Find the LCM of 12, 18 and 30.",
      ["90", "120", "180", "360"], "C", "12 = 2²·3, 18 = 2·3², 30 = 2·3·5; LCM = 2²·3²·5 = 180.", "LCM"),
    Q("quant", "simplification", "easy", "Simplify: 15 + 3 × 4 − 8 ÷ 2",
      ["26", "23", "19", "30"], "B", "BODMAS: 15 + 12 − 4 = 23.", "BODMAS"),
    Q("quant", "partnership", "exam",
      "A invests ₹40,000 for 12 months and B invests ₹60,000 for 6 months. Out of a profit of ₹21,000, A's share is:",
      ["₹9,000", "₹10,500", "₹14,000", "₹12,000"], "D",
      "Ratio = 40000×12 : 60000×6 = 4 : 3. A's share = 4/7 × 21000 = ₹12,000.", "Partnership"),
    Q("quant", "ages", "moderate",
      "A father is three times as old as his son. After 12 years he will be twice as old as the son. The father's present age is:",
      ["36 years", "42 years", "30 years", "48 years"], "A",
      "Let son = s: 3s + 12 = 2(s + 12), so s = 12 and the father is 36.", "Problems on ages"),
    Q("quant", "mixture-alligation", "exam",
      "In what ratio must rice at ₹40/kg be mixed with rice at ₹55/kg to get a mixture worth ₹45/kg?",
      ["1 : 2", "2 : 1", "3 : 1", "1 : 1"], "B", "Alligation: (55 − 45) : (45 − 40) = 10 : 5 = 2 : 1.", "Alligation"),
    Q("quant", "mensuration", "easy", "Find the area of a circle of radius 7 cm (π = 22/7).",
      ["144 cm²", "154 cm²", "164 cm²", "44 cm²"], "B", "πr² = 22/7 × 49 = 154 cm².", "Area of circle"),
    Q("quant", "geometry", "easy", "The angles of a triangle are in the ratio 2 : 3 : 4. The largest angle is:",
      ["60°", "90°", "80°", "100°"], "C", "Sum = 9 parts = 180°, so one part = 20°; largest = 80°.", "Angle sum property"),
    Q("quant", "algebra", "moderate", "If x + 1/x = 4, find x² + 1/x².",
      ["16", "14", "12", "18"], "B", "Square both sides: x² + 2 + 1/x² = 16, so x² + 1/x² = 14.", "Algebraic identities"),
    Q("quant", "probability", "easy", "Two coins are tossed. What is the probability of getting at least one head?",
      ["1/2", "1/4", "2/3", "3/4"], "D", "Only TT has no head: 1 − 1/4 = 3/4.", "Probability"),
    Q("quant", "permutation-combination", "easy", "In how many ways can the letters of the word PLANE be arranged?",
      ["60", "120", "24", "720"], "B", "5 distinct letters: 5! = 120.", "Permutations"),
    Q("quant", "data-interpretation", "moderate",
      "Passengers handled by an airport (in lakh): 2019 – 40, 2020 – 16, 2021 – 24, 2022 – 36. "
      "What was the percentage increase from 2021 to 2022?",
      ["33.3%", "50%", "12%", "40%"], "B", "(36 − 24)/24 × 100 = 50%.", "Percentage change in DI"),

    # ======================= GA & AVIATION — AVIATION =======================
    Q("ga-aviation", "icao", "easy", "The headquarters of the International Civil Aviation Organization (ICAO) is in:",
      ["Geneva", "Montreal", "Paris", "New York"], "B",
      "ICAO, a UN specialised agency, is headquartered in Montreal, Canada.", "ICAO"),
    Q("ga-aviation", "icao", "moderate", "ICAO was established under which convention?",
      ["Warsaw Convention", "Chicago Convention (1944)", "Tokyo Convention", "Montreal Convention (1999)"], "B",
      "The Convention on International Civil Aviation was signed in Chicago on 7 December 1944 and created ICAO.", "Chicago Convention"),
    Q("ga-aviation", "icao", "exam", "Which ICAO Annex deals with Aerodromes?",
      ["Annex 9", "Annex 17", "Annex 14", "Annex 19"], "C",
      "Annex 14 = Aerodromes. Annex 9 = Facilitation, Annex 17 = Security, Annex 19 = Safety Management.", "ICAO Annexes"),
    Q("ga-aviation", "iata", "moderate", "The International Air Transport Association (IATA) is an association of:",
      ["National aviation regulators", "Airlines", "Airport operators", "Aircraft manufacturers"], "B",
      "IATA is the trade association of the world's airlines. Regulators work through ICAO; airports through ACI.", "IATA"),
    Q("ga-aviation", "dgca", "easy", "Which body is the regulator of civil aviation (safety, licensing, airworthiness) in India?",
      ["AAI", "BCAS", "DGCA", "AERA"], "C",
      "The Directorate General of Civil Aviation (DGCA) handles safety regulation, licensing and airworthiness.", "DGCA"),
    Q("ga-aviation", "bcas", "easy", "Which organisation is the regulatory authority for civil aviation security in India?",
      ["DGCA", "BCAS", "CISF", "AAI"], "B",
      "The Bureau of Civil Aviation Security (BCAS) sets security standards. CISF provides security at many airports.", "BCAS"),
    Q("ga-aviation", "aai", "moderate", "The Airports Authority of India (AAI) was constituted in:",
      ["1986", "1995", "2000", "1972"], "B",
      "AAI was formed on 1 April 1995 under the AAI Act 1994 by merging the International Airports Authority of India "
      "and the National Airports Authority.", "AAI"),
    Q("ga-aviation", "aera", "exam", "The Airports Economic Regulatory Authority (AERA) mainly regulates:",
      ["Aircraft airworthiness", "Tariffs for aeronautical services at major airports",
       "Airport security", "Air traffic control procedures"], "B",
      "AERA (set up under the AERA Act 2008) determines tariffs for aeronautical services at major airports.", "AERA"),
    Q("ga-aviation", "airport-codes", "easy", "What is the IATA code of Chennai International Airport?",
      ["CHE", "MAA", "CNN", "MDS"], "B", "Chennai's IATA code is MAA, from its old name Madras.", "IATA airport codes"),
    Q("ga-aviation", "airport-codes", "moderate", "Which IATA code belongs to Kochi (Cochin) International Airport?",
      ["KOC", "CCJ", "COK", "CCU"], "C", "COK is Kochi. CCJ is Kozhikode (Calicut) and CCU is Kolkata.", "IATA airport codes"),
    Q("ga-aviation", "airport-codes", "exam", "ICAO location indicators for airports in India begin with the letter:",
      ["I", "A", "V", "H"], "C",
      "Indian ICAO codes start with V (e.g. VIDP Delhi, VABB Mumbai, VOMM Chennai, VECC Kolkata).", "ICAO location indicators"),
    Q("ga-aviation", "major-indian-airports", "easy", "Netaji Subhas Chandra Bose International Airport is located in:",
      ["Kolkata", "Patna", "Bhubaneswar", "Guwahati"], "A", "Kolkata's airport (IATA: CCU) is named after Netaji Subhas Chandra Bose.", "Indian airports"),
    Q("ga-aviation", "airports-india", "moderate", "Which Indian airport is widely known as the world's first fully solar-powered airport?",
      ["Hyderabad", "Kochi", "Bengaluru", "Ahmedabad"], "B",
      "Cochin International Airport (CIAL) became fully solar-powered in 2015.", "Indian airports"),
    Q("ga-aviation", "civil-aviation-policies", "easy", "The UDAN scheme of the Government of India is associated with:",
      ["Airport privatisation", "Regional air connectivity", "Aircraft manufacturing", "Pilot training"], "B",
      "UDAN (Ude Desh ka Aam Nagrik) is the Regional Connectivity Scheme under the National Civil Aviation Policy 2016.", "UDAN"),
    Q("ga-aviation", "runways", "moderate", "A runway designated '09' at one end will be designated ___ at the opposite end.",
      ["18", "27", "90", "36"], "B",
      "Runway numbers are the magnetic heading ÷ 10. 090° reversed is 270°, so the other end is 27.", "Runway designation"),
    Q("ga-aviation", "aprons", "easy", "The area of an airport where aircraft are parked, loaded, unloaded and refuelled is the:",
      ["Runway", "Taxiway", "Apron", "Clearway"], "C",
      "The apron is the defined area for parking, loading/unloading, refuelling and boarding.", "Aerodrome areas"),
    Q("ga-aviation", "cns-navaids", "moderate", "In an Instrument Landing System (ILS), lateral (left–right) guidance is provided by the:",
      ["Glide slope", "Localizer", "Marker beacon", "DME"], "B",
      "The localizer gives lateral guidance along the runway centreline; the glide slope gives vertical guidance.", "ILS"),
    Q("ga-aviation", "aviation-abbreviations", "easy", "In aviation, VOR stands for:",
      ["Visual Orientation Radar", "VHF Omnidirectional Range", "Vertical Obstacle Reference", "Very high Output Receiver"], "B",
      "VOR = VHF Omnidirectional Range, a radio navigation aid.", "Navigation aids"),
    Q("ga-aviation", "aviation-meteorology", "moderate", "A METAR is:",
      ["A forecast for a flight route", "A routine aerodrome weather observation report",
       "A notice to airmen about hazards", "A flight plan format"], "B",
      "METAR is a routine meteorological report of current aerodrome weather. A TAF is the aerodrome forecast.", "METAR"),
    Q("ga-aviation", "atc-basics", "exam", "Transponder code 7700 indicates:",
      ["Radio communication failure", "Unlawful interference (hijack)", "General emergency", "VFR flight"], "C",
      "7700 = emergency, 7600 = radio failure, 7500 = unlawful interference.", "Emergency squawk codes"),
    Q("ga-aviation", "atc-basics", "moderate", "Which ATC unit controls aircraft on the runway and in the immediate vicinity of the aerodrome?",
      ["Area Control Centre", "Approach Control", "Aerodrome Control (Tower)", "Flight Information Centre"], "C",
      "Aerodrome (tower) control handles runway movements and traffic close to the airport.", "ATC units"),
    Q("ga-aviation", "flight-basics", "easy", "Which force acts opposite to the weight of an aircraft in flight?",
      ["Thrust", "Drag", "Lift", "Friction"], "C", "The four forces are lift vs weight and thrust vs drag.", "Forces on an aircraft"),
    Q("ga-aviation", "flight-basics", "moderate", "An aircraft altimeter works by measuring:",
      ["Air temperature", "Static air pressure", "Engine speed", "Radio signal delay from ground"], "B",
      "A pressure altimeter converts static pressure into altitude (a radio altimeter uses radio signals).", "Altimeter"),
    Q("ga-aviation", "passenger-processing", "easy", "At customs, the Green Channel is meant for passengers who:",
      ["Are transit passengers", "Have nothing to declare", "Carry dutiable goods", "Are diplomats"], "B",
      "Green Channel = nothing to declare; Red Channel = goods to declare.", "Customs channels"),
    Q("ga-aviation", "security-process", "moderate", "The part of an airport beyond the security screening point is called the:",
      ["Landside", "Airside", "Forecourt", "Kerbside"], "B",
      "Airside is the controlled area beyond screening; landside is open to the public.", "Airside and landside"),
    Q("ga-aviation", "terminals", "easy", "A passenger boarding bridge connecting the terminal gate to the aircraft door is also called:",
      ["Aerobridge", "Ramp", "Apron bridge", "Taxi link"], "A",
      "It is commonly called an aerobridge or jet bridge.", "Terminal facilities"),
    Q("ga-aviation", "aviation-safety", "moderate", "The cockpit voice recorder and flight data recorder ('black boxes') are usually painted:",
      ["Black", "Bright orange", "Silver", "Yellow with black stripes"], "B",
      "They are painted bright orange so they can be located easily after an accident.", "Flight recorders"),
    Q("ga-aviation", "airlines-manufacturers", "moderate", "Embraer, a manufacturer of regional jets, is based in:",
      ["Canada", "France", "Brazil", "Italy"], "C", "Embraer is a Brazilian aerospace company.", "Aircraft manufacturers"),
    Q("ga-aviation", "baggage", "easy", "Baggage handed over at check-in and carried in the aircraft hold is called:",
      ["Cabin baggage", "Hold (checked) baggage", "Excess baggage", "Unaccompanied baggage"], "B",
      "Checked or hold baggage travels in the cargo hold; cabin baggage goes with the passenger.", "Baggage"),

    # ======================= GA & AVIATION — STATIC GK =======================
    Q("ga-aviation", "indian-polity", "moderate", "Fundamental Duties were added to the Indian Constitution by the:",
      ["44th Amendment", "42nd Amendment", "73rd Amendment", "86th Amendment"], "B",
      "The 42nd Amendment (1976) added Part IVA (Article 51A) on Fundamental Duties.", "Fundamental Duties"),
    Q("ga-aviation", "indian-polity", "easy", "The Right to Life and Personal Liberty is guaranteed by Article:",
      ["14", "19", "21", "32"], "C", "Article 21 protects life and personal liberty.", "Fundamental Rights"),
    Q("ga-aviation", "indian-geography", "moderate", "The Tropic of Cancer passes through how many Indian states?",
      ["6", "7", "8", "9"], "C",
      "Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram — 8 states.", "Tropic of Cancer"),
    Q("ga-aviation", "general-science", "easy", "Deficiency of Vitamin C causes:",
      ["Rickets", "Scurvy", "Night blindness", "Beriberi"], "B",
      "Scurvy — Vitamin C; rickets — D; night blindness — A; beriberi — B1.", "Vitamins"),
    Q("ga-aviation", "indian-economy", "moderate", "The Reserve Bank of India was established in:",
      ["1935", "1947", "1949", "1969"], "A", "RBI began operations on 1 April 1935; it was nationalised in 1949.", "RBI"),
    Q("ga-aviation", "indian-history", "moderate", "The First Battle of Panipat (1526) was fought between Babur and:",
      ["Rana Sanga", "Ibrahim Lodi", "Hemu", "Sher Shah Suri"], "B",
      "Babur defeated Ibrahim Lodi, founding the Mughal Empire.", "Medieval India"),
    Q("ga-aviation", "government-schemes", "easy", "Pradhan Mantri Jan Dhan Yojana (2014) primarily aims at:",
      ["Rural housing", "Financial inclusion through bank accounts", "Skill development", "Crop insurance"], "B",
      "PMJDY aims to give every household access to a basic bank account.", "Government schemes"),

    # ======================= PHYSICS =======================
    Q("physics", "units-measurements", "easy", "The dimensional formula of force is:",
      ["[MLT⁻²]", "[ML²T⁻²]", "[MLT⁻¹]", "[ML⁻¹T⁻²]"], "A", "F = ma → [M][LT⁻²] = [MLT⁻²].", "Dimensions"),
    Q("physics", "units-measurements", "easy", "Which of the following is NOT a unit of energy?",
      ["Joule", "Electron volt", "Kilowatt-hour", "Watt"], "D", "Watt is the unit of power (J/s).", "Units"),
    Q("physics", "motion", "easy", "A body starts from rest with an acceleration of 2 m/s². The distance covered in 5 s is:",
      ["50 m", "25 m", "10 m", "20 m"], "B", "s = ut + ½at² = 0 + ½ × 2 × 25 = 25 m.", "Equations of motion"),
    Q("physics", "motion", "easy", "For a given launch speed, the horizontal range of a projectile is maximum at an angle of:",
      ["30°", "60°", "45°", "90°"], "C", "R = u² sin 2θ / g is maximum when sin 2θ = 1, i.e. θ = 45°.", "Projectile motion"),
    Q("physics", "laws-of-motion", "moderate", "A force of 10 N acts for 0.5 s on a 2 kg body at rest. Its final velocity is:",
      ["5 m/s", "2.5 m/s", "1 m/s", "10 m/s"], "B", "Impulse = FΔt = 5 N s = mv, so v = 5/2 = 2.5 m/s.", "Impulse–momentum"),
    Q("physics", "laws-of-motion", "easy", "Rocket propulsion is based on:",
      ["Newton's first law", "Pascal's law", "Conservation of linear momentum", "Conservation of energy alone"], "C",
      "Exhaust gases gain backward momentum; the rocket gains equal forward momentum.", "Conservation of momentum"),
    Q("physics", "work-energy-power", "easy", "If the speed of a body is doubled, its kinetic energy becomes:",
      ["2 times", "4 times", "half", "8 times"], "B", "KE = ½mv² ∝ v², so doubling v gives 4 × KE.", "Kinetic energy"),
    Q("physics", "work-energy-power", "moderate",
      "A 50 kg load is lifted through 10 m in 5 s. The power required is (g = 10 m/s²):",
      ["500 W", "2500 W", "1000 W", "100 W"], "C", "P = mgh/t = 50 × 10 × 10 / 5 = 1000 W.", "Power"),
    Q("physics", "rotational-motion", "moderate",
      "The moment of inertia of a thin ring of mass M and radius R about an axis through its centre, perpendicular to its plane, is:",
      ["½MR²", "MR²", "⅔MR²", "⅖MR²"], "B", "All the mass is at distance R, so I = MR².", "Moment of inertia"),
    Q("physics", "rotational-motion", "moderate", "A spinning skater pulls her arms in. Her angular velocity:",
      ["Decreases", "Stays the same", "Increases", "Becomes zero"], "C",
      "Angular momentum Iω is conserved; I decreases, so ω increases.", "Conservation of angular momentum"),
    Q("physics", "system-of-particles", "moderate",
      "Two particles of masses 2 kg and 3 kg are at x = 0 and x = 5 m. The centre of mass is at:",
      ["x = 2.5 m", "x = 2 m", "x = 3 m", "x = 3.5 m"], "C", "x_cm = (2×0 + 3×5)/5 = 3 m.", "Centre of mass"),
    Q("physics", "gravitation", "exam", "At a height equal to the Earth's radius R above the surface, the acceleration due to gravity is:",
      ["g/2", "g/4", "g/9", "2g"], "B", "g' = g R²/(2R)² = g/4.", "Variation of g with height"),
    Q("physics", "gravitation", "easy", "The escape velocity from the Earth's surface is about:",
      ["7.9 km/s", "9.8 km/s", "11.2 km/s", "3.1 km/s"], "C",
      "v_e = √(2gR) ≈ 11.2 km/s. 7.9 km/s is the orbital speed near the surface.", "Escape velocity"),
    Q("physics", "properties-of-matter", "moderate", "Bernoulli's theorem for fluid flow is a statement of the conservation of:",
      ["Mass", "Energy", "Momentum", "Charge"], "B",
      "Pressure energy + kinetic energy + potential energy per unit volume stays constant along a streamline.", "Bernoulli's principle"),
    Q("physics", "properties-of-matter", "moderate",
      "The gauge pressure at a depth of 10 m in water is (ρ = 1000 kg/m³, g = 10 m/s²):",
      ["10⁴ Pa", "10⁵ Pa", "10⁶ Pa", "10³ Pa"], "B", "P = ρgh = 1000 × 10 × 10 = 10⁵ Pa.", "Hydrostatic pressure"),
    Q("physics", "properties-of-matter", "exam", "Young's modulus of a perfectly rigid body is:",
      ["Zero", "Infinite", "1", "Equal to its bulk modulus"], "B",
      "A perfectly rigid body has zero strain for any stress, so Y = stress/strain is infinite.", "Elasticity"),
    Q("physics", "thermodynamics", "moderate", "For an ideal gas in an isothermal process:",
      ["Q = 0", "ΔU = 0", "W = 0", "ΔP = 0"], "B",
      "Internal energy of an ideal gas depends only on temperature, which is constant.", "Isothermal process"),
    Q("physics", "thermodynamics", "exam", "A Carnot engine works between 500 K and 300 K. Its efficiency is:",
      ["60%", "30%", "40%", "25%"], "C", "η = 1 − T₂/T₁ = 1 − 300/500 = 0.4 = 40%.", "Carnot efficiency"),
    Q("physics", "kinetic-theory", "moderate", "If the absolute temperature of a gas is made 4 times, the rms speed of its molecules:",
      ["Doubles", "Becomes 4 times", "Halves", "Is unchanged"], "A", "v_rms = √(3RT/M) ∝ √T; √4 = 2.", "RMS speed"),
    Q("physics", "oscillations", "easy", "If the length of a simple pendulum is made four times, its time period:",
      ["Halves", "Doubles", "Becomes four times", "Is unchanged"], "B", "T = 2π√(l/g) ∝ √l; √4 = 2.", "Simple pendulum"),
    Q("physics", "waves", "easy", "A sound wave of frequency 170 Hz travels at 340 m/s. Its wavelength is:",
      ["0.5 m", "1 m", "2 m", "4 m"], "C", "λ = v/f = 340/170 = 2 m.", "Wave equation"),
    Q("physics", "electrostatics", "easy", "If the distance between two point charges is doubled, the force between them becomes:",
      ["F/2", "F/4", "2F", "4F"], "B", "Coulomb's law: F ∝ 1/r², so doubling r gives F/4.", "Coulomb's law"),
    Q("physics", "electrostatics", "moderate", "Two capacitors of 6 μF each are connected in series. The equivalent capacitance is:",
      ["12 μF", "6 μF", "3 μF", "1.5 μF"], "C", "1/C = 1/6 + 1/6 = 1/3, so C = 3 μF.", "Capacitors in series"),
    Q("physics", "electrostatics", "moderate", "The total electric flux through a closed surface enclosing a charge q is:",
      ["qε₀", "q/ε₀", "Zero", "q/4πε₀"], "B", "Gauss's law: Φ = q_enclosed/ε₀.", "Gauss's law"),
    Q("physics", "current-electricity", "easy", "Resistors of 4 Ω and 12 Ω are connected in parallel. The equivalent resistance is:",
      ["16 Ω", "8 Ω", "3 Ω", "2 Ω"], "C", "R = (4 × 12)/(4 + 12) = 48/16 = 3 Ω.", "Parallel resistors"),
    Q("physics", "current-electricity", "moderate", "The resistance of a 220 V, 100 W bulb is:",
      ["440 Ω", "484 Ω", "2.2 Ω", "48.4 Ω"], "B", "R = V²/P = 220²/100 = 484 Ω.", "Electric power"),
    Q("physics", "moving-charges-magnetism", "moderate",
      "The magnetic field at the centre of a circular loop of radius R carrying current I is:",
      ["μ₀I/2πR", "μ₀I/4R", "μ₀I/2R", "μ₀IR/2"], "C", "From the Biot–Savart law, B = μ₀I/2R at the centre.", "Biot–Savart law"),
    Q("physics", "moving-charges-magnetism", "easy", "The magnetic force on a charge moving parallel to a magnetic field is:",
      ["qvB", "Zero", "Maximum", "qv/B"], "B", "F = qvB sin θ, and θ = 0° gives F = 0.", "Lorentz force"),
    Q("physics", "magnetism", "moderate", "A substance with a small negative magnetic susceptibility is:",
      ["Paramagnetic", "Ferromagnetic", "Diamagnetic", "Ferrimagnetic"], "C",
      "Diamagnetic materials are weakly repelled, with small negative susceptibility.", "Magnetic materials"),
    Q("physics", "emi", "moderate", "Lenz's law is a consequence of the conservation of:",
      ["Charge", "Momentum", "Energy", "Mass"], "C",
      "The induced current opposes the change causing it; otherwise energy would be created from nothing.", "Lenz's law"),
    Q("physics", "alternating-current", "exam", "At resonance in a series LCR circuit, the power factor is:",
      ["0", "0.5", "0.707", "1"], "D", "At resonance X_L = X_C, so Z = R and cos φ = R/Z = 1.", "LCR resonance"),
    Q("physics", "alternating-current", "easy", "A transformer works on the principle of:",
      ["Self-induction", "Mutual induction", "Eddy currents", "Electrostatic induction"], "B",
      "A changing current in the primary induces an emf in the secondary through mutual induction.", "Transformer"),
    Q("physics", "em-waves", "easy", "Which of these electromagnetic waves has the longest wavelength?",
      ["X-rays", "Microwaves", "Infrared", "Radio waves"], "D", "Radio waves have the longest wavelength in the EM spectrum.", "EM spectrum"),
    Q("physics", "ray-optics", "exam", "An object is placed 30 cm in front of a concave mirror of focal length 15 cm. The image is formed:",
      ["30 cm in front of the mirror", "15 cm in front of the mirror", "30 cm behind the mirror", "At infinity"], "A",
      "1/v = 1/f − 1/u = −1/15 + 1/30 = −1/30, so v = −30 cm: real, inverted, same size, at C.", "Mirror formula"),
    Q("physics", "ray-optics", "easy", "The power of a convex lens of focal length 25 cm is:",
      ["+0.25 D", "+4 D", "−4 D", "+25 D"], "B", "P = 1/f (in metres) = 1/0.25 = +4 D.", "Power of a lens"),
    Q("physics", "ray-optics", "moderate", "The speed of light in glass of refractive index 1.5 is (c = 3 × 10⁸ m/s):",
      ["1.5 × 10⁸ m/s", "2 × 10⁸ m/s", "4.5 × 10⁸ m/s", "3 × 10⁸ m/s"], "B", "v = c/n = 3 × 10⁸ / 1.5 = 2 × 10⁸ m/s.", "Refractive index"),
    Q("physics", "wave-optics", "exam",
      "In Young's double-slit experiment, λ = 600 nm, slit separation 0.5 mm and screen distance 1 m. The fringe width is:",
      ["0.6 mm", "1.2 mm", "2.4 mm", "0.3 mm"], "B", "β = λD/d = (600 × 10⁻⁹ × 1)/(0.5 × 10⁻³) = 1.2 × 10⁻³ m.", "Fringe width"),
    Q("physics", "dual-nature", "moderate", "In the photoelectric effect, the maximum kinetic energy of emitted electrons depends on:",
      ["Intensity of light", "Frequency of light", "Time of exposure", "Area of the plate"], "B",
      "K_max = hν − φ; intensity changes the number of electrons, not their maximum energy.", "Photoelectric effect"),
    Q("physics", "dual-nature", "challenging", "The de Broglie wavelength of an electron accelerated through 100 V is approximately:",
      ["1.23 nm", "0.123 nm", "12.3 nm", "0.0123 nm"], "B", "λ = 1.227/√V nm = 1.227/10 ≈ 0.123 nm.", "de Broglie wavelength"),
    Q("physics", "atoms", "moderate", "The energy of the electron in the n = 2 orbit of a hydrogen atom is:",
      ["−13.6 eV", "−3.4 eV", "−1.51 eV", "−6.8 eV"], "B", "Eₙ = −13.6/n² eV = −13.6/4 = −3.4 eV.", "Bohr model"),
    Q("physics", "nuclei", "moderate", "A radioactive sample has a half-life of 10 days. The fraction remaining after 30 days is:",
      ["1/3", "1/6", "1/8", "1/4"], "C", "30 days = 3 half-lives, so (1/2)³ = 1/8 remains.", "Half-life"),
    Q("physics", "semiconductors", "moderate", "Which logic gate gives a LOW output only when all its inputs are HIGH?",
      ["AND", "OR", "NOR", "NAND"], "D", "NAND = NOT(AND): the output is 0 only when every input is 1.", "Logic gates"),
    Q("physics", "semiconductors", "easy", "Which dopant added to silicon produces an n-type semiconductor?",
      ["Boron", "Aluminium", "Phosphorus", "Gallium"], "C",
      "Phosphorus is pentavalent and donates free electrons. Boron, aluminium and gallium give p-type.", "Doping"),
    Q("physics", "semiconductors", "exam", "In a forward-biased p–n junction diode, the width of the depletion layer:",
      ["Increases", "Decreases", "Stays the same", "Becomes infinite"], "B",
      "Forward bias opposes the barrier potential, narrowing the depletion region.", "p–n junction"),

    # ======================= MATHEMATICS =======================
    Q("mathematics", "sets", "easy", "If n(A) = 20, n(B) = 15 and n(A ∩ B) = 5, then n(A ∪ B) is:",
      ["35", "30", "25", "40"], "B", "n(A ∪ B) = 20 + 15 − 5 = 30.", "Union of sets"),
    Q("mathematics", "relations", "moderate", "The number of relations from a set with 2 elements to a set with 3 elements is:",
      ["6", "8", "32", "64"], "D", "A × B has 6 elements; relations are its subsets: 2⁶ = 64.", "Number of relations"),
    Q("mathematics", "functions", "easy", "If f(x) = 2x + 3, then f⁻¹(x) is:",
      ["(x + 3)/2", "(x − 3)/2", "2x − 3", "(x − 2)/3"], "B", "y = 2x + 3 ⇒ x = (y − 3)/2.", "Inverse function"),
    Q("mathematics", "trigonometry", "moderate", "The value of sin 75° is:",
      ["(√6 − √2)/4", "(√3 + 1)/2", "(√6 + √2)/4", "√3/2"], "C",
      "sin(45° + 30°) = sin45 cos30 + cos45 sin30 = (√6 + √2)/4.", "Compound angles"),
    Q("mathematics", "trigonometry", "exam", "The maximum value of 3 sin x + 4 cos x is:",
      ["7", "5", "4", "3"], "B", "Maximum of a sin x + b cos x is √(a² + b²) = 5.", "Range of trig expressions"),
    Q("mathematics", "inverse-trigonometry", "moderate", "tan⁻¹(1) + tan⁻¹(1/√3) equals:",
      ["π/3", "π/2", "5π/12", "7π/12"], "C", "π/4 + π/6 = 5π/12.", "Principal values"),
    Q("mathematics", "inverse-trigonometry", "easy", "For x in [−1, 1], sin⁻¹x + cos⁻¹x equals:",
      ["π", "π/2", "0", "π/4"], "B", "This is a standard identity: sin⁻¹x + cos⁻¹x = π/2.", "Inverse trig identities"),
    Q("mathematics", "complex-numbers", "moderate", "The value of i²⁰²⁶ is:",
      ["1", "i", "−1", "−i"], "C", "2026 = 4 × 506 + 2, so i²⁰²⁶ = i² = −1.", "Powers of i"),
    Q("mathematics", "complex-numbers", "easy", "The modulus of 3 + 4i is:",
      ["7", "25", "√7", "5"], "D", "|3 + 4i| = √(9 + 16) = 5.", "Modulus"),
    Q("mathematics", "quadratic-equations", "moderate", "If α and β are the roots of x² − 5x + 6 = 0, then α² + β² is:",
      ["25", "13", "12", "19"], "B", "α + β = 5, αβ = 6; α² + β² = 25 − 12 = 13.", "Sum and product of roots"),
    Q("mathematics", "permutations-combinations", "easy", "The value of ⁸C₃ is:",
      ["336", "56", "24", "70"], "B", "⁸C₃ = (8 × 7 × 6)/(3 × 2 × 1) = 56.", "Combinations"),
    Q("mathematics", "binomial-theorem", "easy", "The number of terms in the expansion of (x + y)¹⁰ is:",
      ["10", "11", "12", "20"], "B", "(x + y)ⁿ has n + 1 terms.", "Binomial expansion"),
    Q("mathematics", "binomial-theorem", "moderate", "The coefficient of the middle term in the expansion of (1 + x)⁶ is:",
      ["15", "6", "20", "35"], "C", "The middle term is T₄ = ⁶C₃ x³, coefficient 20.", "Middle term"),
    Q("mathematics", "sequences-series", "moderate", "In an AP, the 3rd term is 8 and the 7th term is 20. The 10th term is:",
      ["32", "26", "30", "29"], "D", "4d = 12 ⇒ d = 3, a = 2; a₁₀ = 2 + 27 = 29.", "Arithmetic progression"),
    Q("mathematics", "sequences-series", "easy", "The sum of the infinite GP 1 + 1/2 + 1/4 + … is:",
      ["1", "2", "3/2", "Infinite"], "B", "S∞ = a/(1 − r) = 1/(1 − ½) = 2.", "Infinite GP"),
    Q("mathematics", "straight-lines", "easy", "The slope of the line through (2, 3) and (4, 7) is:",
      ["1/2", "−2", "2", "4"], "C", "m = (7 − 3)/(4 − 2) = 2.", "Slope"),
    Q("mathematics", "straight-lines", "moderate", "The perpendicular distance of (3, 4) from the line 3x + 4y − 5 = 0 is:",
      ["5", "4", "20", "3"], "B", "|9 + 16 − 5|/√(9 + 16) = 20/5 = 4.", "Distance of a point from a line"),
    Q("mathematics", "circles", "moderate", "The centre and radius of x² + y² − 4x + 6y − 12 = 0 are:",
      ["(−2, 3), 5", "(2, −3), 25", "(2, −3), 5", "(2, 3), 5"], "C",
      "Centre (−g, −f) = (2, −3); r = √(4 + 9 + 12) = 5.", "Equation of a circle"),
    Q("mathematics", "conic-sections", "easy", "The focus of the parabola y² = 8x is:",
      ["(0, 2)", "(2, 0)", "(8, 0)", "(4, 0)"], "B", "y² = 4ax with a = 2 gives focus (a, 0) = (2, 0).", "Parabola"),
    Q("mathematics", "conic-sections", "exam", "The eccentricity of the ellipse x²/25 + y²/16 = 1 is:",
      ["4/5", "3/5", "5/3", "9/25"], "B", "e = √(1 − b²/a²) = √(1 − 16/25) = 3/5.", "Ellipse"),
    Q("mathematics", "limits", "easy", "lim (x → 0) sin 3x / x equals:",
      ["1", "0", "3", "1/3"], "C", "sin 3x / x = 3 · (sin 3x / 3x) → 3.", "Standard limits"),
    Q("mathematics", "limits", "easy", "lim (x → 2) (x² − 4)/(x − 2) equals:",
      ["2", "4", "0", "Does not exist"], "B", "Factor: (x − 2)(x + 2)/(x − 2) = x + 2 → 4.", "Limits by factorisation"),
    Q("mathematics", "continuity", "moderate", "The function f(x) = |x| at x = 0 is:",
      ["Discontinuous", "Continuous and differentiable", "Continuous but not differentiable", "Differentiable but not continuous"], "C",
      "|x| is continuous at 0, but the left derivative (−1) differs from the right derivative (+1).", "Continuity and differentiability"),
    Q("mathematics", "differentiation", "moderate", "d/dx (x² sin x) is:",
      ["2x cos x", "2x sin x + x² cos x", "2x sin x − x² cos x", "x² cos x"], "B",
      "Product rule: (x²)′ sin x + x² (sin x)′.", "Product rule"),
    Q("mathematics", "differentiation", "easy", "d/dx (tan⁻¹ x) is:",
      ["1/(1 + x²)", "1/√(1 − x²)", "−1/(1 + x²)", "sec² x"], "A", "Standard derivative.", "Derivatives of inverse trig"),
    Q("mathematics", "applications-derivatives", "moderate", "The minimum value of x² − 6x + 10 is:",
      ["10", "1", "3", "−1"], "B", "x² − 6x + 10 = (x − 3)² + 1, minimum 1 at x = 3.", "Maxima and minima"),
    Q("mathematics", "applications-derivatives", "easy", "The slope of the tangent to y = x³ at x = 2 is:",
      ["8", "6", "12", "4"], "C", "dy/dx = 3x² = 12 at x = 2.", "Tangents"),
    Q("mathematics", "indefinite-integration", "moderate", "∫ x eˣ dx equals:",
      ["eˣ(x + 1) + C", "x eˣ + C", "eˣ(x − 1) + C", "x² eˣ/2 + C"], "C",
      "By parts: x eˣ − ∫ eˣ dx = eˣ(x − 1) + C.", "Integration by parts"),
    Q("mathematics", "definite-integration", "exam", "∫₀^{π/2} sin² x dx equals:",
      ["π/2", "π/4", "1", "1/2"], "B",
      "Using ∫₀^a f(x) dx = ∫₀^a f(a − x) dx, the sin² and cos² integrals are equal and sum to π/2, so each is π/4.",
      "Properties of definite integrals"),
    Q("mathematics", "definite-integration", "easy", "∫₋₁¹ x³ dx equals:",
      ["1/2", "1", "2", "0"], "D", "x³ is an odd function, so its integral over a symmetric interval is 0.", "Odd functions"),
    Q("mathematics", "applications-integration", "exam", "The area enclosed between y = x² and y = x is:",
      ["1/3", "1/6", "1/2", "1/12"], "B", "They meet at x = 0 and 1: ∫₀¹ (x − x²) dx = 1/2 − 1/3 = 1/6.", "Area between curves"),
    Q("mathematics", "differential-equations", "moderate",
      "The order and degree of (d²y/dx²)³ + (dy/dx)⁴ + y = 0 are:",
      ["Order 3, degree 2", "Order 2, degree 3", "Order 2, degree 4", "Order 4, degree 2"], "B",
      "Highest derivative is d²y/dx² (order 2); its power is 3 (degree 3).", "Order and degree"),
    Q("mathematics", "differential-equations", "easy", "The general solution of dy/dx = y is:",
      ["y = x + C", "y = Ceˣ", "y = Cx", "y = eˣ + C"], "B", "dy/y = dx ⇒ ln y = x + c ⇒ y = Ceˣ.", "Variable separable"),
    Q("mathematics", "differential-equations", "exam", "The integrating factor of dy/dx + y/x = x² is:",
      ["1/x", "eˣ", "x", "log x"], "C", "IF = e^{∫(1/x)dx} = e^{ln x} = x.", "Linear differential equations"),
    Q("mathematics", "determinants", "moderate", "If A is a 3 × 3 matrix with |A| = 4, then |2A| is:",
      ["8", "16", "32", "64"], "C", "|kA| = kⁿ|A| = 2³ × 4 = 32.", "Properties of determinants"),
    Q("mathematics", "determinants", "exam", "If A is a 3 × 3 matrix with |A| = 5, then |adj A| is:",
      ["5", "25", "125", "1/5"], "B", "|adj A| = |A|ⁿ⁻¹ = 5² = 25.", "Adjoint"),
    Q("mathematics", "matrices", "easy", "For matrices A and B for which AB is defined, (AB)ᵀ equals:",
      ["AᵀBᵀ", "BᵀAᵀ", "BA", "AB"], "B", "The transpose of a product reverses the order: (AB)ᵀ = BᵀAᵀ.", "Transpose"),
    Q("mathematics", "vectors", "easy", "If a = i + 2j + 3k and b = 2i − j + k, then a · b is:",
      ["5", "1", "3", "0"], "C", "a · b = 2 − 2 + 3 = 3.", "Dot product"),
    Q("mathematics", "vectors", "moderate", "If a and b are perpendicular unit vectors, |a × b| is:",
      ["0", "1", "√2", "2"], "B", "|a × b| = |a||b| sin 90° = 1.", "Cross product"),
    Q("mathematics", "3d-geometry", "moderate", "The direction cosines of a line equally inclined to the three coordinate axes are:",
      ["±1, ±1, ±1", "±1/√3, ±1/√3, ±1/√3", "±1/3, ±1/3, ±1/3", "±1/√2, ±1/√2, 0"], "B",
      "l = m = n and l² + m² + n² = 1, so each is ±1/√3.", "Direction cosines"),
    Q("mathematics", "3d-geometry", "exam", "The distance of the point (1, 2, 3) from the plane 2x − y + 2z − 3 = 0 is:",
      ["3", "2", "1", "1/3"], "C", "|2 − 2 + 6 − 3|/√(4 + 1 + 4) = 3/3 = 1.", "Distance from a plane"),
    Q("mathematics", "probability", "moderate", "A and B are independent events with P(A) = 0.4 and P(B) = 0.5. P(A ∪ B) is:",
      ["0.9", "0.7", "0.2", "0.5"], "B", "P(A ∩ B) = 0.2, so P(A ∪ B) = 0.4 + 0.5 − 0.2 = 0.7.", "Independent events"),
    Q("mathematics", "probability", "moderate",
      "A bag has 3 red and 2 black balls. Two balls are drawn without replacement. The probability that both are red is:",
      ["9/25", "3/5", "3/10", "1/5"], "C", "(3/5) × (2/4) = 3/10.", "Conditional probability"),
    Q("mathematics", "probability", "challenging",
      "Box I has 2 red and 3 blue balls; Box II has 4 red and 1 blue. A box is chosen at random and a ball drawn is red. "
      "The probability that it came from Box II is:",
      ["1/3", "2/3", "4/5", "1/2"], "B",
      "Bayes: (½ × 4/5) / (½ × 2/5 + ½ × 4/5) = 0.4/0.6 = 2/3.", "Bayes' theorem"),
    Q("mathematics", "statistics", "moderate", "The variance of 2, 4, 6, 8, 10 is:",
      ["6", "40", "8", "√8"], "C", "Mean 6; squared deviations 16, 4, 0, 4, 16 sum to 40; 40/5 = 8.", "Variance"),

    # ======================= BUSINESS MANAGEMENT =======================
    Q("management", "scientific-management", "easy", "Who is known as the father of Scientific Management?",
      ["Henri Fayol", "F. W. Taylor", "Max Weber", "Elton Mayo"], "B",
      "Frederick Winslow Taylor developed scientific management (time and motion study, differential piece rate).", "Scientific management"),
    Q("management", "fayol-principles", "easy", "How many principles of management did Henri Fayol give?",
      ["12", "10", "14", "16"], "C", "Fayol gave 14 general principles of management.", "Fayol's principles"),
    Q("management", "fayol-principles", "moderate", "\"An employee should receive orders from only one superior\" is Fayol's principle of:",
      ["Unity of direction", "Unity of command", "Scalar chain", "Centralisation"], "B",
      "Unity of command = one boss. Unity of direction = one head and one plan for a group of activities with the same objective.",
      "Unity of command"),
    Q("management", "fayol-principles", "exam", "Fayol's concept of 'gang plank' is related to the principle of:",
      ["Unity of command", "Order", "Scalar chain", "Equity"], "C",
      "The gang plank allows direct communication between same-level employees, as a shortcut in the scalar chain.", "Scalar chain"),
    Q("management", "bureaucracy", "easy", "The bureaucratic model of organisation is associated with:",
      ["Max Weber", "Peter Drucker", "Abraham Maslow", "Chester Barnard"], "A",
      "Max Weber proposed bureaucracy based on rules, hierarchy and impersonality.", "Bureaucracy"),
    Q("management", "human-relations", "moderate", "The Hawthorne experiments, which led to the human relations approach, were conducted by:",
      ["F. W. Taylor", "Elton Mayo", "Henry Gantt", "Douglas McGregor"], "B",
      "Elton Mayo and colleagues found that social and psychological factors affect productivity.", "Hawthorne studies"),
    Q("management", "maslow", "easy", "In Maslow's hierarchy, the highest-level need is:",
      ["Esteem", "Safety", "Self-actualisation", "Social"], "C",
      "Order: physiological → safety → social → esteem → self-actualisation.", "Maslow's hierarchy"),
    Q("management", "herzberg", "moderate", "According to Herzberg, which of these is a hygiene (maintenance) factor?",
      ["Recognition", "Achievement", "Salary", "Responsibility"], "C",
      "Hygiene factors (salary, working conditions, policy) prevent dissatisfaction; motivators include achievement and recognition.",
      "Two-factor theory"),
    Q("management", "mcgregor", "moderate", "McGregor's Theory X assumes that the average employee:",
      ["Seeks responsibility", "Dislikes work and must be controlled", "Is self-directed", "Is creative and innovative"], "B",
      "Theory X is the traditional, pessimistic view; Theory Y assumes people like work and seek responsibility.", "Theory X and Y"),
    Q("management", "theory-z", "moderate", "Theory Z, based on Japanese management practices, was given by:",
      ["William Ouchi", "Douglas McGregor", "Rensis Likert", "Frederick Herzberg"], "A",
      "William Ouchi proposed Theory Z (1981), stressing long-term employment and collective decisions.", "Theory Z"),
    Q("management", "levels-roles", "exam", "In Mintzberg's managerial roles, 'spokesperson' belongs to which category?",
      ["Interpersonal", "Decisional", "Informational", "Technical"], "C",
      "Informational roles: monitor, disseminator, spokesperson.", "Mintzberg's roles"),
    Q("management", "planning", "moderate", "The concept of Management by Objectives (MBO) was popularised by:",
      ["Peter Drucker", "Henri Fayol", "Philip Kotler", "Herbert Simon"], "A",
      "Peter Drucker introduced MBO in The Practice of Management (1954).", "MBO"),
    Q("management", "planning", "easy", "Which is known as the primary function of management?",
      ["Organising", "Staffing", "Planning", "Controlling"], "C",
      "Planning comes first; all other functions are carried out within the framework of plans.", "Primacy of planning"),
    Q("management", "strategic-management", "exam", "The concept of 'core competence' was given by:",
      ["Michael Porter", "C. K. Prahalad and Gary Hamel", "Igor Ansoff", "Peter Drucker"], "B",
      "Prahalad and Hamel introduced core competence in 1990.", "Core competence"),
    Q("management", "controlling", "moderate", "The first step in the controlling process is:",
      ["Measuring actual performance", "Taking corrective action", "Setting performance standards", "Analysing deviations"], "C",
      "Standards must be set before performance can be measured and compared.", "Controlling process"),
    Q("management", "organizing", "exam", "In delegation, which of the following cannot be delegated?",
      ["Authority", "Accountability", "Work", "Duties"], "B",
      "Authority is delegated, but the manager remains accountable for the result.", "Delegation"),
    Q("management", "organizing", "moderate", "'Span of control' refers to:",
      ["The number of levels in an organisation",
       "The number of subordinates a manager can supervise effectively",
       "The area of a manager's authority", "The duration of a manager's tenure"], "B",
      "Span of management is the number of subordinates reporting to one manager.", "Span of control"),
    Q("management", "communication", "easy", "'Grapevine' refers to:",
      ["Formal written communication", "Informal communication", "Downward communication", "Mass communication"], "B",
      "Grapevine is the informal network through which information spreads.", "Informal communication"),
    Q("management", "leadership-styles", "easy", "Free-rein leadership is also called:",
      ["Autocratic", "Democratic", "Laissez-faire", "Paternalistic"], "C",
      "Under laissez-faire leadership the group is given freedom to decide.", "Leadership styles"),
    Q("management", "situational-leadership", "moderate", "The situational leadership model is associated with:",
      ["Hersey and Blanchard", "Blake and Mouton", "Taylor and Gilbreth", "Maslow and Alderfer"], "A",
      "Hersey and Blanchard linked leadership style to follower readiness.", "Situational leadership"),
    Q("management", "trait-theory", "moderate", "The trait theory of leadership assumes that:",
      ["Leaders are made through training", "Leaders possess certain inborn qualities",
       "Leadership depends on the situation", "Leadership depends on followers only"], "B",
      "Trait theory holds that leaders are born with qualities such as intelligence and self-confidence.", "Trait theory"),
    Q("management", "selection", "moderate", "Which HR process is described as a 'negative' process?",
      ["Recruitment", "Selection", "Training", "Induction"], "B",
      "Recruitment attracts applicants (positive); selection rejects unsuitable ones (negative).", "Recruitment vs selection"),
    Q("management", "training", "exam", "Training given in a setting that replicates the actual workplace, away from the shop floor, is called:",
      ["Apprenticeship", "Vestibule training", "Job rotation", "Coaching"], "B",
      "Vestibule training uses a replica of the work environment; the others are on-the-job methods.", "Training methods"),
    Q("management", "performance-appraisal", "moderate", "In 360-degree appraisal, feedback is collected from:",
      ["Only the immediate supervisor", "Supervisors, peers, subordinates and others",
       "Only the HR department", "Only customers"], "B",
      "360-degree feedback gathers views from all around the employee.", "Performance appraisal"),
    Q("management", "marketing-mix", "moderate", "The 4 Ps classification of the marketing mix was popularised by:",
      ["Philip Kotler", "E. Jerome McCarthy", "Neil Borden", "Theodore Levitt"], "B",
      "McCarthy grouped the marketing mix into Product, Price, Place and Promotion (1960).", "Marketing mix"),
    Q("management", "promotion", "easy", "Which of the following is NOT an element of the promotion mix?",
      ["Advertising", "Personal selling", "Packaging", "Sales promotion"], "C",
      "Promotion mix = advertising, personal selling, sales promotion and public relations. Packaging is part of product.", "Promotion mix"),
    Q("management", "branding", "moderate", "A brand, or part of a brand, that is given legal protection is called a:",
      ["Brand mark", "Trademark", "Label", "Logo"], "B", "A registered trademark has exclusive legal protection.", "Branding"),
    Q("management", "directing", "easy", "Which of the following is NOT an element of directing?",
      ["Supervision", "Motivation", "Staffing", "Leadership"], "C",
      "Directing = supervision, motivation, leadership and communication. Staffing is a separate function.", "Directing"),
    Q("management", "coordination", "moderate", "Which is regarded as the 'essence of management'?",
      ["Planning", "Coordination", "Controlling", "Staffing"], "B",
      "Coordination integrates all functions and runs through the whole management process.", "Coordination"),
    Q("management", "decision-making", "exam", "The concept of 'bounded rationality' in decision making was given by:",
      ["Herbert Simon", "Peter Drucker", "Henri Fayol", "Chester Barnard"], "A",
      "Herbert Simon argued that decision makers 'satisfice' because of limited information and capacity.", "Bounded rationality"),
    Q("management", "mis", "moderate", "The main purpose of a Management Information System (MIS) is to:",
      ["Replace managers", "Provide timely, relevant information for decision making",
       "Record only financial transactions", "Train employees"], "B",
      "MIS gives managers the information they need for planning, control and decisions.", "MIS"),
]
