-- GENERATED by content/build_seed.py — do not edit by hand.
-- Original demo questions (source = 'demo'), written for this platform. Not official AAI questions.

insert into questions (subject_id, topic_id, question_text, option_a, option_b, option_c, option_d,
  correct_option, explanation, concept, difficulty, source, is_verified, tags)
select s.id, t.id, v.q, v.a, v.b, v.c, v.d, v.ans, v.expl, v.concept, v.diff::difficulty_level,
  'demo', true, v.tags::text[]
from (values
  ('english', 'synonyms', 'Choose the word most similar in meaning to CANDID.', 'Frank', 'Rude', 'Careless', 'Secretive', 'A', 'Candid means open and honest in speech, i.e. frank.', 'Synonyms', 'easy', '{}'),
  ('english', 'synonyms', 'Choose the word most similar in meaning to METICULOUS.', 'Hasty', 'Painstaking', 'Careless', 'Indifferent', 'B', 'Meticulous means showing great attention to detail — painstaking.', 'Synonyms', 'moderate', '{}'),
  ('english', 'antonyms', 'Choose the word opposite in meaning to SCARCE.', 'Insufficient', 'Meagre', 'Abundant', 'Rare', 'C', 'Scarce means in short supply; its opposite is abundant.', 'Antonyms', 'easy', '{}'),
  ('english', 'antonyms', 'Choose the word opposite in meaning to EPHEMERAL.', 'Transient', 'Fleeting', 'Brief', 'Permanent', 'D', 'Ephemeral means lasting a very short time; the opposite is permanent. The other three are synonyms.', 'Antonyms', 'moderate', '{}'),
  ('english', 'antonyms', 'Choose the word opposite in meaning to RELUCTANT.', 'Eager', 'Unwilling', 'Hesitant', 'Averse', 'A', 'Reluctant means unwilling; its opposite is eager.', 'Antonyms', 'easy', '{}'),
  ('english', 'idioms-phrases', 'Choose the meaning of the idiom: to burn the midnight oil', 'To start a quarrel', 'To work or study late into the night', 'To celebrate a success', 'To waste resources', 'B', 'To burn the midnight oil is to stay up late working or studying.', 'Idioms', 'easy', '{}'),
  ('english', 'idioms-phrases', 'Choose the meaning of the idiom: a blessing in disguise', 'A hidden danger', 'An obvious advantage', 'Something that seems bad at first but turns out to be good', 'An unexpected gift from a stranger', 'C', 'A blessing in disguise is an apparent misfortune that later proves beneficial.', 'Idioms', 'moderate', '{}'),
  ('english', 'one-word-substitution', 'One word for: a person who can speak two languages fluently.', 'Interpreter', 'Linguist', 'Polyglot', 'Bilingual', 'D', 'Bilingual = fluent in two languages. A polyglot knows many languages.', 'One-word substitution', 'easy', '{}'),
  ('english', 'one-word-substitution', 'One word for: a large shed in which aircraft are housed and repaired.', 'Hangar', 'Depot', 'Garage', 'Hanger', 'A', 'Hangar (with -ar) is the aircraft shed. Hanger (with -er) is something you hang clothes on.', 'One-word substitution', 'moderate', '{}'),
  ('english', 'spelling', 'Choose the correctly spelt word.', 'Accommadation', 'Accommodation', 'Acommodation', 'Accomodation', 'B', 'Accommodation has double c and double m.', 'Spelling', 'moderate', '{}'),
  ('english', 'articles', 'Fill in the blank: He is ___ honest man.', 'a', 'the', 'an', 'no article', 'C', '''Honest'' begins with a vowel sound (the h is silent), so ''an'' is used.', 'Articles', 'easy', '{}'),
  ('english', 'prepositions', 'Fill in the blank: The flight was delayed ___ bad weather.', 'despite', 'since', 'because', 'owing to', 'D', '''Owing to'' is a preposition meaning ''because of''. ''Because'' alone needs ''of''; ''despite'' reverses the meaning.', 'Prepositions', 'moderate', '{}'),
  ('english', 'subject-verb-agreement', 'Fill in the blank: Neither the pilot nor the crew members ___ aware of the change in schedule.', 'were', 'was', 'has been', 'is', 'A', 'With neither…nor, the verb agrees with the nearer subject. ''Crew members'' is plural, so ''were''.', 'Subject-verb agreement', 'exam', '{}'),
  ('english', 'tenses', 'Fill in the blank: By the time we reached the airport, the flight ___.', 'left', 'had left', 'was leaving', 'has left', 'B', 'The earlier of two past actions takes the past perfect: had left.', 'Past perfect tense', 'moderate', '{}'),
  ('english', 'active-passive', 'Choose the passive form: The controller cleared the aircraft for take-off.', 'The aircraft had been cleared for take-off by the controller.', 'The aircraft is cleared for take-off by the controller.', 'The aircraft was cleared for take-off by the controller.', 'The aircraft was being cleared for take-off by the controller.', 'C', 'Simple past active (cleared) becomes was + past participle (was cleared).', 'Active and passive voice', 'moderate', '{}'),
  ('english', 'direct-indirect', 'Choose the indirect form: He said, "I am tired."', 'He said that I am tired.', 'He said that he is tired.', 'He told that he was tired.', 'He said that he was tired.', 'D', 'Reporting verb in past: ''am'' becomes ''was'' and ''I'' becomes ''he''. ''Told'' needs an object.', 'Direct and indirect speech', 'moderate', '{}'),
  ('english', 'error-detection', 'Find the part with an error: One of my friends (A) / are working (B) / at the Delhi airport. (C) / No error (D)', 'A', 'B', 'C', 'D', 'B', 'The subject is ''One'', which is singular, so it should be ''is working''.', 'Error detection', 'exam', '{}'),
  ('english', 'sentence-improvement', 'Improve the underlined part: If I was a pilot, I would fly across the world. (underlined: If I was)', 'No improvement', 'If I were', 'If I had been', 'If I am', 'B', 'Imaginary or hypothetical conditions take the subjunctive ''were'' for all persons.', 'Subjunctive mood', 'exam', '{}'),
  ('english', 'fill-blanks', 'Fill in the blank: The new terminal was designed to ___ ten million passengers a year.', 'accumulate', 'alleviate', 'accommodate', 'assimilate', 'C', 'Accommodate = provide space for. The others do not fit the sense.', 'Vocabulary in context', 'moderate', '{}'),
  ('english', 'fill-blanks', 'Fill in the blank: Safety is the ___ priority of every airline.', 'partial', 'parallel', 'paranoid', 'paramount', 'D', 'Paramount means of supreme importance.', 'Vocabulary in context', 'easy', '{}'),
  ('english', 'vocabulary', 'Choose the correct word: The medicine had a good ___ on him.', 'effect', 'afect', 'effort', 'affect', 'A', '''Effect'' (noun) is the result; ''affect'' is usually a verb.', 'Confusable words', 'easy', '{}'),
  ('english', 'para-jumbles', 'Passengers first arrive at the terminal. Arrange the rest in order:
P: They then collect their boarding passes at the check-in counter.
Q: After security screening, they proceed to the boarding gate.
R: Checked baggage is handed over at the same counter.
S: Finally, they board the aircraft when the gate opens.', 'RPQS', 'PRQS', 'QPRS', 'PQRS', 'B', '''The same counter'' in R refers back to P, so P–R; security (Q) comes before boarding (S).', 'Para jumbles', 'exam', '{}'),
  ('english', 'reading-comprehension', 'Read the passage and answer.
"Radar allows air traffic controllers to see aircraft even in cloud or at night. Primary radar detects signals reflected from the aircraft''s body, while secondary radar relies on a transponder on board, which replies with the aircraft''s identity and altitude."
According to the passage, secondary radar depends on:', 'Daylight', 'Reflection from the aircraft''s body', 'A transponder on the aircraft', 'Clear weather', 'C', 'The passage states that secondary radar relies on the on-board transponder.', 'Reading comprehension', 'moderate', '{}'),
  ('reasoning', 'number-series', 'Find the next term: 3, 6, 12, 24, ?', '36', '30', '42', '48', 'D', 'Each term is double the previous one: 24 × 2 = 48.', 'Geometric series', 'easy', '{}'),
  ('reasoning', 'number-series', 'Find the next term: 2, 6, 12, 20, 30, ?', '42', '36', '44', '40', 'A', 'Differences are 4, 6, 8, 10, so the next is 12: 30 + 12 = 42.', 'Difference series', 'moderate', '{}'),
  ('reasoning', 'number-series', 'Find the next term: 1, 8, 27, 64, ?', '100', '125', '81', '216', 'B', 'These are cubes 1³, 2³, 3³, 4³; next is 5³ = 125.', 'Cube series', 'easy', '{}'),
  ('reasoning', 'alphabet-series', 'Find the next term: A, C, F, J, O, ?', 'T', 'S', 'U', 'V', 'C', 'Gaps are +2, +3, +4, +5, then +6. O (15) + 6 = U (21).', 'Alphabet series', 'moderate', '{}'),
  ('reasoning', 'letter-number-symbol-series', 'Find the next term: AZ, BY, CX, ?', 'DV', 'DX', 'EW', 'DW', 'D', 'First letters go forward (A, B, C, D); second letters go backward (Z, Y, X, W).', 'Letter pairs', 'easy', '{}'),
  ('reasoning', 'coding-decoding', 'If AIRPORT is coded as BJSQPSU, how is RUNWAY coded?', 'SVOXBZ', 'TVOXBZ', 'SVOXAZ', 'SVPXBZ', 'A', 'Each letter moves one step forward: R→S, U→V, N→O, W→X, A→B, Y→Z.', 'Letter shift coding', 'moderate', '{}'),
  ('reasoning', 'coding-decoding', 'If FLIGHT is written as THGILF, how is PILOT written?', 'OTLIP', 'TOLIP', 'TOLPI', 'TPLOI', 'B', 'The word is simply reversed: PILOT → TOLIP.', 'Reverse coding', 'easy', '{}'),
  ('reasoning', 'blood-relations', 'Pointing to a man, Riya said, "He is the son of my grandfather''s only son." How is the man related to Riya?', 'Uncle', 'Father', 'Brother', 'Cousin', 'C', 'Her grandfather''s only son is her father; her father''s son is her brother.', 'Blood relations', 'moderate', '{}'),
  ('reasoning', 'blood-relations', 'A is B''s sister. C is B''s mother. D is C''s father. How is A related to D?', 'Grandmother', 'Daughter', 'Niece', 'Granddaughter', 'D', 'A is C''s daughter, and C is D''s child, so A (female) is D''s granddaughter.', 'Blood relations', 'exam', '{}'),
  ('reasoning', 'direction-sense', 'A man walks 4 km north, turns right and walks 3 km, then turns right again and walks 4 km. Where is he from the start?', '3 km East', '3 km West', '5 km North-East', '7 km East', 'A', 'North 4, east 3, south 4: the north and south cancel, leaving 3 km east.', 'Direction sense', 'moderate', '{}'),
  ('reasoning', 'direction-sense', 'Rahul faces east. He turns 90° clockwise and then 180° anticlockwise. Which direction is he facing now?', 'East', 'North', 'South', 'West', 'B', 'East → (90° clockwise) South → (180°) North.', 'Turns', 'easy', '{}'),
  ('reasoning', 'syllogism', 'Statements: All pilots are officers. Some officers are engineers.
Conclusions: I. Some pilots are engineers. II. Some engineers are officers.', 'Only I follows', 'Only II follows', 'Both follow', 'Neither follows', 'B', 'II is the conversion of ''some officers are engineers''. I is not certain — the engineer-officers may not be pilots.', 'Syllogism', 'exam', '{}'),
  ('reasoning', 'syllogism', 'Statements: All runways are paved. No paved surface is grass.
Conclusions: I. No runway is grass. II. Some grass is runway.', 'Only I follows', 'Only II follows', 'Both follow', 'Neither follows', 'A', 'All runways lie inside ''paved'', which has no overlap with grass, so no runway is grass; II contradicts I.', 'Syllogism', 'moderate', '{}'),
  ('reasoning', 'analogy', 'Pilot : Cockpit :: Chef : ?', 'Kitchen', 'Waiter', 'Menu', 'Restaurant', 'A', 'A pilot works in the cockpit; a chef works in the kitchen.', 'Workplace analogy', 'easy', '{}'),
  ('reasoning', 'odd-one-out', 'Find the odd one out: 27, 64, 125, 144', '125', '144', '64', '27', 'B', '27, 64 and 125 are cubes; 144 is a square (12²), not a cube.', 'Number classification', 'moderate', '{}'),
  ('reasoning', 'classification', 'Find the odd one out: Mercury, Venus, Moon, Mars', 'Mercury', 'Venus', 'Moon', 'Mars', 'C', 'The Moon is a natural satellite; the others are planets.', 'Classification', 'easy', '{}'),
  ('reasoning', 'ranking', 'In a row of 40 students, Anil is 12th from the left. What is his position from the right?', '28th', '30th', '27th', '29th', 'D', 'Position from right = 40 − 12 + 1 = 29.', 'Ranking', 'easy', '{}'),
  ('reasoning', 'seating-arrangement', 'P, Q, R, S and T sit in a row facing north. R sits at the extreme left end and S at the extreme right end. Q sits immediately to the right of P. T sits immediately to the left of S. Who sits in the middle?', 'Q', 'P', 'T', 'R', 'A', 'Positions: R(1), S(5), T(4). P and Q take 2 and 3 with Q to the right of P, so the order is R P Q T S.', 'Linear arrangement', 'exam', '{}'),
  ('reasoning', 'mathematical-operations', 'If ''+'' means ''×'', ''−'' means ''+'', ''×'' means ''÷'' and ''÷'' means ''−'', find the value of 8 + 3 − 12 × 4 ÷ 5.', '24', '22', '19', '26', 'B', 'The expression becomes 8 × 3 + 12 ÷ 4 − 5 = 24 + 3 − 5 = 22.', 'Symbol substitution', 'moderate', '{}'),
  ('reasoning', 'inequalities', 'Statements: P > Q ≥ R = S < T. Conclusions: I. P > S  II. T > R', 'Only I follows', 'Only II follows', 'Both follow', 'Neither follows', 'C', 'P > Q ≥ R = S gives P > S. T > S and S = R give T > R. Both follow.', 'Inequalities', 'moderate', '{}'),
  ('reasoning', 'statement-conclusions', 'Statement: All passengers must complete security screening before boarding.
Conclusions: I. Screening is required for boarding. II. Every screened passenger will definitely board.', 'Only I follows', 'Only II follows', 'Both follow', 'Neither follows', 'A', 'Screening is a necessary condition, not a guarantee of boarding.', 'Statement and conclusions', 'moderate', '{}'),
  ('reasoning', 'mirror-water-images', 'A clock shows 3:15. What time does its mirror image show?', '8:45', '9:45', '8:15', '9:15', 'A', 'Mirror time = 11:60 − 3:15 = 8:45.', 'Clock mirror image', 'exam', '{}'),
  ('reasoning', 'logical-word-order', 'Arrange in a logical order: 1. Landing 2. Take-off 3. Boarding 4. Check-in 5. Taxiing', '3, 4, 5, 2, 1', '4, 3, 5, 2, 1', '4, 5, 3, 2, 1', '4, 3, 2, 5, 1', 'B', 'Check-in → boarding → taxiing → take-off → landing.', 'Logical sequence', 'easy', '{}'),
  ('quant', 'percentage', 'What is 25% of 480?', '96', '125', '120', '110', 'C', '25% = 1/4, and 480 ÷ 4 = 120.', 'Percentage', 'easy', '{}'),
  ('quant', 'percentage', 'A price is increased by 20% and then decreased by 20%. The net change is:', '4% increase', 'No change', '2% decrease', '4% decrease', 'D', 'Net = 20 − 20 − (20 × 20)/100 = −4%, i.e. a 4% decrease.', 'Successive percentage change', 'moderate', '{}'),
  ('quant', 'profit-loss', 'An article bought for ₹800 is sold for ₹920. Find the profit percentage.', '15%', '18%', '20%', '12%', 'A', 'Profit = 120; 120/800 × 100 = 15%.', 'Profit percentage', 'easy', '{}'),
  ('quant', 'discount', 'The marked price is ₹1,500. Successive discounts of 10% and 20% are given. Find the selling price.', '₹1,050', '₹1,080', '₹1,200', '₹1,100', 'B', '1500 × 0.9 × 0.8 = ₹1,080.', 'Successive discounts', 'moderate', '{}'),
  ('quant', 'simple-interest', 'Find the simple interest on ₹5,000 at 8% per annum for 3 years.', '₹1,250', '₹1,100', '₹1,200', '₹1,300', 'C', 'SI = PRT/100 = 5000 × 8 × 3 / 100 = ₹1,200.', 'Simple interest', 'easy', '{}'),
  ('quant', 'compound-interest', 'Find the compound interest on ₹10,000 at 10% per annum for 2 years, compounded annually.', '₹2,010', '₹2,000', '₹2,200', '₹2,100', 'D', 'Amount = 10000 × 1.1² = 12,100; CI = ₹2,100.', 'Compound interest', 'moderate', '{}'),
  ('quant', 'ratio-proportion', '₹1,200 is divided in the ratio 3 : 5. Find the larger share.', '₹750', '₹450', '₹800', '₹700', 'A', 'Larger share = 5/8 × 1200 = ₹750.', 'Ratio division', 'easy', '{}'),
  ('quant', 'average', 'The average of 5 numbers is 42. When one number is removed, the average of the rest is 40. Find the number removed.', '48', '50', '46', '52', 'B', 'Total 5 × 42 = 210; remaining 4 × 40 = 160; removed = 50.', 'Average', 'moderate', '{}'),
  ('quant', 'time-work', 'A can finish a job in 12 days and B in 18 days. Working together, how long will they take?', '8 days', '7.5 days', '7.2 days', '6 days', 'C', '1/12 + 1/18 = 5/36 per day, so 36/5 = 7.2 days.', 'Combined work', 'moderate', '{}'),
  ('quant', 'pipes-cisterns', 'A pipe fills a tank in 6 hours and another empties it in 9 hours. If both are opened together, the tank fills in:', '15 hours', '3 hours', '12 hours', '18 hours', 'D', 'Net rate = 1/6 − 1/9 = 1/18, so 18 hours.', 'Pipes and cisterns', 'moderate', '{}'),
  ('quant', 'time-speed-distance', 'Express 72 km/h in m/s.', '20 m/s', '22 m/s', '18 m/s', '25 m/s', 'A', '72 × 5/18 = 20 m/s.', 'Unit conversion', 'easy', '{}'),
  ('quant', 'time-speed-distance', 'A 150 m long train runs at 54 km/h. How long does it take to cross a pole?', '8 s', '10 s', '15 s', '12 s', 'B', '54 km/h = 15 m/s; time = 150/15 = 10 s.', 'Train problems', 'moderate', '{}'),
  ('quant', 'boats-streams', 'A boat''s downstream speed is 18 km/h and upstream speed is 12 km/h. Find the speed of the stream.', '2 km/h', '6 km/h', '3 km/h', '15 km/h', 'C', 'Stream = (18 − 12)/2 = 3 km/h.', 'Boats and streams', 'moderate', '{}'),
  ('quant', 'number-system', 'Find the LCM of 12, 18 and 30.', '90', '360', '120', '180', 'D', '12 = 2²·3, 18 = 2·3², 30 = 2·3·5; LCM = 2²·3²·5 = 180.', 'LCM', 'easy', '{}'),
  ('quant', 'simplification', 'Simplify: 15 + 3 × 4 − 8 ÷ 2', '23', '30', '19', '26', 'A', 'BODMAS: 15 + 12 − 4 = 23.', 'BODMAS', 'easy', '{}'),
  ('quant', 'partnership', 'A invests ₹40,000 for 12 months and B invests ₹60,000 for 6 months. Out of a profit of ₹21,000, A''s share is:', '₹9,000', '₹12,000', '₹14,000', '₹10,500', 'B', 'Ratio = 40000×12 : 60000×6 = 4 : 3. A''s share = 4/7 × 21000 = ₹12,000.', 'Partnership', 'exam', '{}'),
  ('quant', 'ages', 'A father is three times as old as his son. After 12 years he will be twice as old as the son. The father''s present age is:', '30 years', '48 years', '36 years', '42 years', 'C', 'Let son = s: 3s + 12 = 2(s + 12), so s = 12 and the father is 36.', 'Problems on ages', 'moderate', '{}'),
  ('quant', 'mixture-alligation', 'In what ratio must rice at ₹40/kg be mixed with rice at ₹55/kg to get a mixture worth ₹45/kg?', '1 : 2', '3 : 1', '1 : 1', '2 : 1', 'D', 'Alligation: (55 − 45) : (45 − 40) = 10 : 5 = 2 : 1.', 'Alligation', 'exam', '{}'),
  ('quant', 'mensuration', 'Find the area of a circle of radius 7 cm (π = 22/7).', '154 cm²', '44 cm²', '164 cm²', '144 cm²', 'A', 'πr² = 22/7 × 49 = 154 cm².', 'Area of circle', 'easy', '{}'),
  ('quant', 'geometry', 'The angles of a triangle are in the ratio 2 : 3 : 4. The largest angle is:', '90°', '80°', '100°', '60°', 'B', 'Sum = 9 parts = 180°, so one part = 20°; largest = 80°.', 'Angle sum property', 'easy', '{}'),
  ('quant', 'algebra', 'If x + 1/x = 4, find x² + 1/x².', '18', '12', '14', '16', 'C', 'Square both sides: x² + 2 + 1/x² = 16, so x² + 1/x² = 14.', 'Algebraic identities', 'moderate', '{}'),
  ('quant', 'probability', 'Two coins are tossed. What is the probability of getting at least one head?', '1/4', '1/2', '2/3', '3/4', 'D', 'Only TT has no head: 1 − 1/4 = 3/4.', 'Probability', 'easy', '{}'),
  ('quant', 'permutation-combination', 'In how many ways can the letters of the word PLANE be arranged?', '120', '24', '60', '720', 'A', '5 distinct letters: 5! = 120.', 'Permutations', 'easy', '{}'),
  ('quant', 'data-interpretation', 'Passengers handled by an airport (in lakh): 2019 – 40, 2020 – 16, 2021 – 24, 2022 – 36. What was the percentage increase from 2021 to 2022?', '12%', '50%', '40%', '33.3%', 'B', '(36 − 24)/24 × 100 = 50%.', 'Percentage change in DI', 'moderate', '{}'),
  ('ga-aviation', 'icao', 'The headquarters of the International Civil Aviation Organization (ICAO) is in:', 'Paris', 'Geneva', 'Montreal', 'New York', 'C', 'ICAO, a UN specialised agency, is headquartered in Montreal, Canada.', 'ICAO', 'easy', '{}'),
  ('ga-aviation', 'icao', 'ICAO was established under which convention?', 'Warsaw Convention', 'Tokyo Convention', 'Montreal Convention (1999)', 'Chicago Convention (1944)', 'D', 'The Convention on International Civil Aviation was signed in Chicago on 7 December 1944 and created ICAO.', 'Chicago Convention', 'moderate', '{}'),
  ('ga-aviation', 'icao', 'Which ICAO Annex deals with Aerodromes?', 'Annex 14', 'Annex 9', 'Annex 17', 'Annex 19', 'A', 'Annex 14 = Aerodromes. Annex 9 = Facilitation, Annex 17 = Security, Annex 19 = Safety Management.', 'ICAO Annexes', 'exam', '{}'),
  ('ga-aviation', 'iata', 'The International Air Transport Association (IATA) is an association of:', 'Airport operators', 'Airlines', 'Aircraft manufacturers', 'National aviation regulators', 'B', 'IATA is the trade association of the world''s airlines. Regulators work through ICAO; airports through ACI.', 'IATA', 'moderate', '{}'),
  ('ga-aviation', 'dgca', 'Which body is the regulator of civil aviation (safety, licensing, airworthiness) in India?', 'AAI', 'AERA', 'DGCA', 'BCAS', 'C', 'The Directorate General of Civil Aviation (DGCA) handles safety regulation, licensing and airworthiness.', 'DGCA', 'easy', '{}'),
  ('ga-aviation', 'bcas', 'Which organisation is the regulatory authority for civil aviation security in India?', 'CISF', 'DGCA', 'AAI', 'BCAS', 'D', 'The Bureau of Civil Aviation Security (BCAS) sets security standards. CISF provides security at many airports.', 'BCAS', 'easy', '{}'),
  ('ga-aviation', 'aai', 'The Airports Authority of India (AAI) was constituted in:', '1995', '2000', '1986', '1972', 'A', 'AAI was formed on 1 April 1995 under the AAI Act 1994 by merging the International Airports Authority of India and the National Airports Authority.', 'AAI', 'moderate', '{}'),
  ('ga-aviation', 'aera', 'The Airports Economic Regulatory Authority (AERA) mainly regulates:', 'Air traffic control procedures', 'Tariffs for aeronautical services at major airports', 'Aircraft airworthiness', 'Airport security', 'B', 'AERA (set up under the AERA Act 2008) determines tariffs for aeronautical services at major airports.', 'AERA', 'exam', '{}'),
  ('ga-aviation', 'airport-codes', 'What is the IATA code of Chennai International Airport?', 'CHE', 'CNN', 'MAA', 'MDS', 'C', 'Chennai''s IATA code is MAA, from its old name Madras.', 'IATA airport codes', 'easy', '{}'),
  ('ga-aviation', 'airport-codes', 'Which IATA code belongs to Kochi (Cochin) International Airport?', 'CCU', 'CCJ', 'KOC', 'COK', 'D', 'COK is Kochi. CCJ is Kozhikode (Calicut) and CCU is Kolkata.', 'IATA airport codes', 'moderate', '{}'),
  ('ga-aviation', 'airport-codes', 'ICAO location indicators for airports in India begin with the letter:', 'V', 'A', 'I', 'H', 'A', 'Indian ICAO codes start with V (e.g. VIDP Delhi, VABB Mumbai, VOMM Chennai, VECC Kolkata).', 'ICAO location indicators', 'exam', '{}'),
  ('ga-aviation', 'major-indian-airports', 'Netaji Subhas Chandra Bose International Airport is located in:', 'Guwahati', 'Kolkata', 'Bhubaneswar', 'Patna', 'B', 'Kolkata''s airport (IATA: CCU) is named after Netaji Subhas Chandra Bose.', 'Indian airports', 'easy', '{}'),
  ('ga-aviation', 'airports-india', 'Which Indian airport is widely known as the world''s first fully solar-powered airport?', 'Hyderabad', 'Bengaluru', 'Kochi', 'Ahmedabad', 'C', 'Cochin International Airport (CIAL) became fully solar-powered in 2015.', 'Indian airports', 'moderate', '{}'),
  ('ga-aviation', 'civil-aviation-policies', 'The UDAN scheme of the Government of India is associated with:', 'Pilot training', 'Airport privatisation', 'Aircraft manufacturing', 'Regional air connectivity', 'D', 'UDAN (Ude Desh ka Aam Nagrik) is the Regional Connectivity Scheme under the National Civil Aviation Policy 2016.', 'UDAN', 'easy', '{}'),
  ('ga-aviation', 'runways', 'A runway designated ''09'' at one end will be designated ___ at the opposite end.', '27', '90', '18', '36', 'A', 'Runway numbers are the magnetic heading ÷ 10. 090° reversed is 270°, so the other end is 27.', 'Runway designation', 'moderate', '{}'),
  ('ga-aviation', 'aprons', 'The area of an airport where aircraft are parked, loaded, unloaded and refuelled is the:', 'Clearway', 'Apron', 'Runway', 'Taxiway', 'B', 'The apron is the defined area for parking, loading/unloading, refuelling and boarding.', 'Aerodrome areas', 'easy', '{}'),
  ('ga-aviation', 'cns-navaids', 'In an Instrument Landing System (ILS), lateral (left–right) guidance is provided by the:', 'DME', 'Marker beacon', 'Localizer', 'Glide slope', 'C', 'The localizer gives lateral guidance along the runway centreline; the glide slope gives vertical guidance.', 'ILS', 'moderate', '{}'),
  ('ga-aviation', 'aviation-abbreviations', 'In aviation, VOR stands for:', 'Vertical Obstacle Reference', 'Very high Output Receiver', 'Visual Orientation Radar', 'VHF Omnidirectional Range', 'D', 'VOR = VHF Omnidirectional Range, a radio navigation aid.', 'Navigation aids', 'easy', '{}'),
  ('ga-aviation', 'aviation-meteorology', 'A METAR is:', 'A routine aerodrome weather observation report', 'A forecast for a flight route', 'A flight plan format', 'A notice to airmen about hazards', 'A', 'METAR is a routine meteorological report of current aerodrome weather. A TAF is the aerodrome forecast.', 'METAR', 'moderate', '{}'),
  ('ga-aviation', 'atc-basics', 'Transponder code 7700 indicates:', 'Unlawful interference (hijack)', 'General emergency', 'VFR flight', 'Radio communication failure', 'B', '7700 = emergency, 7600 = radio failure, 7500 = unlawful interference.', 'Emergency squawk codes', 'exam', '{}'),
  ('ga-aviation', 'atc-basics', 'Which ATC unit controls aircraft on the runway and in the immediate vicinity of the aerodrome?', 'Area Control Centre', 'Approach Control', 'Aerodrome Control (Tower)', 'Flight Information Centre', 'C', 'Aerodrome (tower) control handles runway movements and traffic close to the airport.', 'ATC units', 'moderate', '{}'),
  ('ga-aviation', 'flight-basics', 'Which force acts opposite to the weight of an aircraft in flight?', 'Thrust', 'Friction', 'Drag', 'Lift', 'D', 'The four forces are lift vs weight and thrust vs drag.', 'Forces on an aircraft', 'easy', '{}'),
  ('ga-aviation', 'flight-basics', 'An aircraft altimeter works by measuring:', 'Static air pressure', 'Air temperature', 'Radio signal delay from ground', 'Engine speed', 'A', 'A pressure altimeter converts static pressure into altitude (a radio altimeter uses radio signals).', 'Altimeter', 'moderate', '{}'),
  ('ga-aviation', 'passenger-processing', 'At customs, the Green Channel is meant for passengers who:', 'Are diplomats', 'Have nothing to declare', 'Carry dutiable goods', 'Are transit passengers', 'B', 'Green Channel = nothing to declare; Red Channel = goods to declare.', 'Customs channels', 'easy', '{}'),
  ('ga-aviation', 'security-process', 'The part of an airport beyond the security screening point is called the:', 'Kerbside', 'Landside', 'Airside', 'Forecourt', 'C', 'Airside is the controlled area beyond screening; landside is open to the public.', 'Airside and landside', 'moderate', '{}'),
  ('ga-aviation', 'terminals', 'A passenger boarding bridge connecting the terminal gate to the aircraft door is also called:', 'Apron bridge', 'Taxi link', 'Ramp', 'Aerobridge', 'D', 'It is commonly called an aerobridge or jet bridge.', 'Terminal facilities', 'easy', '{}'),
  ('ga-aviation', 'aviation-safety', 'The cockpit voice recorder and flight data recorder (''black boxes'') are usually painted:', 'Bright orange', 'Black', 'Yellow with black stripes', 'Silver', 'A', 'They are painted bright orange so they can be located easily after an accident.', 'Flight recorders', 'moderate', '{}'),
  ('ga-aviation', 'airlines-manufacturers', 'Embraer, a manufacturer of regional jets, is based in:', 'Italy', 'Brazil', 'Canada', 'France', 'B', 'Embraer is a Brazilian aerospace company.', 'Aircraft manufacturers', 'moderate', '{}'),
  ('ga-aviation', 'baggage', 'Baggage handed over at check-in and carried in the aircraft hold is called:', 'Excess baggage', 'Cabin baggage', 'Hold (checked) baggage', 'Unaccompanied baggage', 'C', 'Checked or hold baggage travels in the cargo hold; cabin baggage goes with the passenger.', 'Baggage', 'easy', '{}'),
  ('ga-aviation', 'indian-polity', 'Fundamental Duties were added to the Indian Constitution by the:', '44th Amendment', '73rd Amendment', '86th Amendment', '42nd Amendment', 'D', 'The 42nd Amendment (1976) added Part IVA (Article 51A) on Fundamental Duties.', 'Fundamental Duties', 'moderate', '{}'),
  ('ga-aviation', 'indian-polity', 'The Right to Life and Personal Liberty is guaranteed by Article:', '21', '19', '32', '14', 'A', 'Article 21 protects life and personal liberty.', 'Fundamental Rights', 'easy', '{}'),
  ('ga-aviation', 'indian-geography', 'The Tropic of Cancer passes through how many Indian states?', '7', '8', '6', '9', 'B', 'Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram — 8 states.', 'Tropic of Cancer', 'moderate', '{}'),
  ('ga-aviation', 'general-science', 'Deficiency of Vitamin C causes:', 'Night blindness', 'Beriberi', 'Scurvy', 'Rickets', 'C', 'Scurvy — Vitamin C; rickets — D; night blindness — A; beriberi — B1.', 'Vitamins', 'easy', '{}'),
  ('ga-aviation', 'indian-economy', 'The Reserve Bank of India was established in:', '1969', '1947', '1949', '1935', 'D', 'RBI began operations on 1 April 1935; it was nationalised in 1949.', 'RBI', 'moderate', '{}'),
  ('ga-aviation', 'indian-history', 'The First Battle of Panipat (1526) was fought between Babur and:', 'Ibrahim Lodi', 'Sher Shah Suri', 'Rana Sanga', 'Hemu', 'A', 'Babur defeated Ibrahim Lodi, founding the Mughal Empire.', 'Medieval India', 'moderate', '{}'),
  ('ga-aviation', 'government-schemes', 'Pradhan Mantri Jan Dhan Yojana (2014) primarily aims at:', 'Skill development', 'Financial inclusion through bank accounts', 'Crop insurance', 'Rural housing', 'B', 'PMJDY aims to give every household access to a basic bank account.', 'Government schemes', 'easy', '{}'),
  ('physics', 'units-measurements', 'The dimensional formula of force is:', '[MLT⁻¹]', '[ML²T⁻²]', '[MLT⁻²]', '[ML⁻¹T⁻²]', 'C', 'F = ma → [M][LT⁻²] = [MLT⁻²].', 'Dimensions', 'easy', '{}'),
  ('physics', 'units-measurements', 'Which of the following is NOT a unit of energy?', 'Electron volt', 'Kilowatt-hour', 'Joule', 'Watt', 'D', 'Watt is the unit of power (J/s).', 'Units', 'easy', '{}'),
  ('physics', 'motion', 'A body starts from rest with an acceleration of 2 m/s². The distance covered in 5 s is:', '25 m', '50 m', '20 m', '10 m', 'A', 's = ut + ½at² = 0 + ½ × 2 × 25 = 25 m.', 'Equations of motion', 'easy', '{}'),
  ('physics', 'motion', 'For a given launch speed, the horizontal range of a projectile is maximum at an angle of:', '30°', '45°', '90°', '60°', 'B', 'R = u² sin 2θ / g is maximum when sin 2θ = 1, i.e. θ = 45°.', 'Projectile motion', 'easy', '{}'),
  ('physics', 'laws-of-motion', 'A force of 10 N acts for 0.5 s on a 2 kg body at rest. Its final velocity is:', '10 m/s', '1 m/s', '2.5 m/s', '5 m/s', 'C', 'Impulse = FΔt = 5 N s = mv, so v = 5/2 = 2.5 m/s.', 'Impulse–momentum', 'moderate', '{}'),
  ('physics', 'laws-of-motion', 'Rocket propulsion is based on:', 'Conservation of energy alone', 'Newton''s first law', 'Pascal''s law', 'Conservation of linear momentum', 'D', 'Exhaust gases gain backward momentum; the rocket gains equal forward momentum.', 'Conservation of momentum', 'easy', '{}'),
  ('physics', 'work-energy-power', 'If the speed of a body is doubled, its kinetic energy becomes:', '4 times', '8 times', '2 times', 'half', 'A', 'KE = ½mv² ∝ v², so doubling v gives 4 × KE.', 'Kinetic energy', 'easy', '{}'),
  ('physics', 'work-energy-power', 'A 50 kg load is lifted through 10 m in 5 s. The power required is (g = 10 m/s²):', '500 W', '1000 W', '100 W', '2500 W', 'B', 'P = mgh/t = 50 × 10 × 10 / 5 = 1000 W.', 'Power', 'moderate', '{}'),
  ('physics', 'rotational-motion', 'The moment of inertia of a thin ring of mass M and radius R about an axis through its centre, perpendicular to its plane, is:', '½MR²', '⅖MR²', 'MR²', '⅔MR²', 'C', 'All the mass is at distance R, so I = MR².', 'Moment of inertia', 'moderate', '{}'),
  ('physics', 'rotational-motion', 'A spinning skater pulls her arms in. Her angular velocity:', 'Decreases', 'Becomes zero', 'Stays the same', 'Increases', 'D', 'Angular momentum Iω is conserved; I decreases, so ω increases.', 'Conservation of angular momentum', 'moderate', '{}'),
  ('physics', 'system-of-particles', 'Two particles of masses 2 kg and 3 kg are at x = 0 and x = 5 m. The centre of mass is at:', 'x = 3 m', 'x = 3.5 m', 'x = 2 m', 'x = 2.5 m', 'A', 'x_cm = (2×0 + 3×5)/5 = 3 m.', 'Centre of mass', 'moderate', '{}'),
  ('physics', 'gravitation', 'At a height equal to the Earth''s radius R above the surface, the acceleration due to gravity is:', 'g/2', 'g/4', 'g/9', '2g', 'B', 'g'' = g R²/(2R)² = g/4.', 'Variation of g with height', 'exam', '{}'),
  ('physics', 'gravitation', 'The escape velocity from the Earth''s surface is about:', '3.1 km/s', '7.9 km/s', '11.2 km/s', '9.8 km/s', 'C', 'v_e = √(2gR) ≈ 11.2 km/s. 7.9 km/s is the orbital speed near the surface.', 'Escape velocity', 'easy', '{}'),
  ('physics', 'properties-of-matter', 'Bernoulli''s theorem for fluid flow is a statement of the conservation of:', 'Mass', 'Momentum', 'Charge', 'Energy', 'D', 'Pressure energy + kinetic energy + potential energy per unit volume stays constant along a streamline.', 'Bernoulli''s principle', 'moderate', '{}'),
  ('physics', 'properties-of-matter', 'The gauge pressure at a depth of 10 m in water is (ρ = 1000 kg/m³, g = 10 m/s²):', '10⁵ Pa', '10⁶ Pa', '10³ Pa', '10⁴ Pa', 'A', 'P = ρgh = 1000 × 10 × 10 = 10⁵ Pa.', 'Hydrostatic pressure', 'moderate', '{}'),
  ('physics', 'properties-of-matter', 'Young''s modulus of a perfectly rigid body is:', '1', 'Infinite', 'Equal to its bulk modulus', 'Zero', 'B', 'A perfectly rigid body has zero strain for any stress, so Y = stress/strain is infinite.', 'Elasticity', 'exam', '{}'),
  ('physics', 'thermodynamics', 'For an ideal gas in an isothermal process:', 'ΔP = 0', 'W = 0', 'ΔU = 0', 'Q = 0', 'C', 'Internal energy of an ideal gas depends only on temperature, which is constant.', 'Isothermal process', 'moderate', '{}'),
  ('physics', 'thermodynamics', 'A Carnot engine works between 500 K and 300 K. Its efficiency is:', '60%', '30%', '25%', '40%', 'D', 'η = 1 − T₂/T₁ = 1 − 300/500 = 0.4 = 40%.', 'Carnot efficiency', 'exam', '{}'),
  ('physics', 'kinetic-theory', 'If the absolute temperature of a gas is made 4 times, the rms speed of its molecules:', 'Doubles', 'Is unchanged', 'Becomes 4 times', 'Halves', 'A', 'v_rms = √(3RT/M) ∝ √T; √4 = 2.', 'RMS speed', 'moderate', '{}'),
  ('physics', 'oscillations', 'If the length of a simple pendulum is made four times, its time period:', 'Is unchanged', 'Doubles', 'Becomes four times', 'Halves', 'B', 'T = 2π√(l/g) ∝ √l; √4 = 2.', 'Simple pendulum', 'easy', '{}'),
  ('physics', 'waves', 'A sound wave of frequency 170 Hz travels at 340 m/s. Its wavelength is:', '4 m', '1 m', '2 m', '0.5 m', 'C', 'λ = v/f = 340/170 = 2 m.', 'Wave equation', 'easy', '{}'),
  ('physics', 'electrostatics', 'If the distance between two point charges is doubled, the force between them becomes:', '2F', 'F/2', '4F', 'F/4', 'D', 'Coulomb''s law: F ∝ 1/r², so doubling r gives F/4.', 'Coulomb''s law', 'easy', '{}'),
  ('physics', 'electrostatics', 'Two capacitors of 6 μF each are connected in series. The equivalent capacitance is:', '3 μF', '1.5 μF', '6 μF', '12 μF', 'A', '1/C = 1/6 + 1/6 = 1/3, so C = 3 μF.', 'Capacitors in series', 'moderate', '{}'),
  ('physics', 'electrostatics', 'The total electric flux through a closed surface enclosing a charge q is:', 'Zero', 'q/ε₀', 'qε₀', 'q/4πε₀', 'B', 'Gauss''s law: Φ = q_enclosed/ε₀.', 'Gauss''s law', 'moderate', '{}'),
  ('physics', 'current-electricity', 'Resistors of 4 Ω and 12 Ω are connected in parallel. The equivalent resistance is:', '16 Ω', '8 Ω', '3 Ω', '2 Ω', 'C', 'R = (4 × 12)/(4 + 12) = 48/16 = 3 Ω.', 'Parallel resistors', 'easy', '{}'),
  ('physics', 'current-electricity', 'The resistance of a 220 V, 100 W bulb is:', '440 Ω', '2.2 Ω', '48.4 Ω', '484 Ω', 'D', 'R = V²/P = 220²/100 = 484 Ω.', 'Electric power', 'moderate', '{}'),
  ('physics', 'moving-charges-magnetism', 'The magnetic field at the centre of a circular loop of radius R carrying current I is:', 'μ₀I/2R', 'μ₀I/4R', 'μ₀I/2πR', 'μ₀IR/2', 'A', 'From the Biot–Savart law, B = μ₀I/2R at the centre.', 'Biot–Savart law', 'moderate', '{}'),
  ('physics', 'moving-charges-magnetism', 'The magnetic force on a charge moving parallel to a magnetic field is:', 'qv/B', 'Zero', 'Maximum', 'qvB', 'B', 'F = qvB sin θ, and θ = 0° gives F = 0.', 'Lorentz force', 'easy', '{}'),
  ('physics', 'magnetism', 'A substance with a small negative magnetic susceptibility is:', 'Ferrimagnetic', 'Ferromagnetic', 'Diamagnetic', 'Paramagnetic', 'C', 'Diamagnetic materials are weakly repelled, with small negative susceptibility.', 'Magnetic materials', 'moderate', '{}'),
  ('physics', 'emi', 'Lenz''s law is a consequence of the conservation of:', 'Momentum', 'Mass', 'Charge', 'Energy', 'D', 'The induced current opposes the change causing it; otherwise energy would be created from nothing.', 'Lenz''s law', 'moderate', '{}'),
  ('physics', 'alternating-current', 'At resonance in a series LCR circuit, the power factor is:', '1', '0.5', '0', '0.707', 'A', 'At resonance X_L = X_C, so Z = R and cos φ = R/Z = 1.', 'LCR resonance', 'exam', '{}'),
  ('physics', 'alternating-current', 'A transformer works on the principle of:', 'Electrostatic induction', 'Mutual induction', 'Self-induction', 'Eddy currents', 'B', 'A changing current in the primary induces an emf in the secondary through mutual induction.', 'Transformer', 'easy', '{}'),
  ('physics', 'em-waves', 'Which of these electromagnetic waves has the longest wavelength?', 'Microwaves', 'X-rays', 'Radio waves', 'Infrared', 'C', 'Radio waves have the longest wavelength in the EM spectrum.', 'EM spectrum', 'easy', '{}'),
  ('physics', 'ray-optics', 'An object is placed 30 cm in front of a concave mirror of focal length 15 cm. The image is formed:', '15 cm in front of the mirror', '30 cm behind the mirror', 'At infinity', '30 cm in front of the mirror', 'D', '1/v = 1/f − 1/u = −1/15 + 1/30 = −1/30, so v = −30 cm: real, inverted, same size, at C.', 'Mirror formula', 'exam', '{}'),
  ('physics', 'ray-optics', 'The power of a convex lens of focal length 25 cm is:', '+4 D', '+25 D', '+0.25 D', '−4 D', 'A', 'P = 1/f (in metres) = 1/0.25 = +4 D.', 'Power of a lens', 'easy', '{}'),
  ('physics', 'ray-optics', 'The speed of light in glass of refractive index 1.5 is (c = 3 × 10⁸ m/s):', '1.5 × 10⁸ m/s', '2 × 10⁸ m/s', '3 × 10⁸ m/s', '4.5 × 10⁸ m/s', 'B', 'v = c/n = 3 × 10⁸ / 1.5 = 2 × 10⁸ m/s.', 'Refractive index', 'moderate', '{}'),
  ('physics', 'wave-optics', 'In Young''s double-slit experiment, λ = 600 nm, slit separation 0.5 mm and screen distance 1 m. The fringe width is:', '0.3 mm', '2.4 mm', '1.2 mm', '0.6 mm', 'C', 'β = λD/d = (600 × 10⁻⁹ × 1)/(0.5 × 10⁻³) = 1.2 × 10⁻³ m.', 'Fringe width', 'exam', '{}'),
  ('physics', 'dual-nature', 'In the photoelectric effect, the maximum kinetic energy of emitted electrons depends on:', 'Area of the plate', 'Intensity of light', 'Time of exposure', 'Frequency of light', 'D', 'K_max = hν − φ; intensity changes the number of electrons, not their maximum energy.', 'Photoelectric effect', 'moderate', '{}'),
  ('physics', 'dual-nature', 'The de Broglie wavelength of an electron accelerated through 100 V is approximately:', '0.123 nm', '0.0123 nm', '12.3 nm', '1.23 nm', 'A', 'λ = 1.227/√V nm = 1.227/10 ≈ 0.123 nm.', 'de Broglie wavelength', 'challenging', '{}'),
  ('physics', 'atoms', 'The energy of the electron in the n = 2 orbit of a hydrogen atom is:', '−13.6 eV', '−3.4 eV', '−6.8 eV', '−1.51 eV', 'B', 'Eₙ = −13.6/n² eV = −13.6/4 = −3.4 eV.', 'Bohr model', 'moderate', '{}'),
  ('physics', 'nuclei', 'A radioactive sample has a half-life of 10 days. The fraction remaining after 30 days is:', '1/6', '1/4', '1/8', '1/3', 'C', '30 days = 3 half-lives, so (1/2)³ = 1/8 remains.', 'Half-life', 'moderate', '{}'),
  ('physics', 'semiconductors', 'Which logic gate gives a LOW output only when all its inputs are HIGH?', 'OR', 'NOR', 'AND', 'NAND', 'D', 'NAND = NOT(AND): the output is 0 only when every input is 1.', 'Logic gates', 'moderate', '{}'),
  ('physics', 'semiconductors', 'Which dopant added to silicon produces an n-type semiconductor?', 'Phosphorus', 'Gallium', 'Aluminium', 'Boron', 'A', 'Phosphorus is pentavalent and donates free electrons. Boron, aluminium and gallium give p-type.', 'Doping', 'easy', '{}'),
  ('physics', 'semiconductors', 'In a forward-biased p–n junction diode, the width of the depletion layer:', 'Stays the same', 'Decreases', 'Becomes infinite', 'Increases', 'B', 'Forward bias opposes the barrier potential, narrowing the depletion region.', 'p–n junction', 'exam', '{}'),
  ('mathematics', 'sets', 'If n(A) = 20, n(B) = 15 and n(A ∩ B) = 5, then n(A ∪ B) is:', '35', '25', '30', '40', 'C', 'n(A ∪ B) = 20 + 15 − 5 = 30.', 'Union of sets', 'easy', '{}'),
  ('mathematics', 'relations', 'The number of relations from a set with 2 elements to a set with 3 elements is:', '6', '32', '8', '64', 'D', 'A × B has 6 elements; relations are its subsets: 2⁶ = 64.', 'Number of relations', 'moderate', '{}'),
  ('mathematics', 'functions', 'If f(x) = 2x + 3, then f⁻¹(x) is:', '(x − 3)/2', '2x − 3', '(x + 3)/2', '(x − 2)/3', 'A', 'y = 2x + 3 ⇒ x = (y − 3)/2.', 'Inverse function', 'easy', '{}'),
  ('mathematics', 'trigonometry', 'The value of sin 75° is:', '(√6 − √2)/4', '(√6 + √2)/4', '√3/2', '(√3 + 1)/2', 'B', 'sin(45° + 30°) = sin45 cos30 + cos45 sin30 = (√6 + √2)/4.', 'Compound angles', 'moderate', '{}'),
  ('mathematics', 'trigonometry', 'The maximum value of 3 sin x + 4 cos x is:', '4', '7', '5', '3', 'C', 'Maximum of a sin x + b cos x is √(a² + b²) = 5.', 'Range of trig expressions', 'exam', '{}'),
  ('mathematics', 'inverse-trigonometry', 'tan⁻¹(1) + tan⁻¹(1/√3) equals:', 'π/3', 'π/2', '7π/12', '5π/12', 'D', 'π/4 + π/6 = 5π/12.', 'Principal values', 'moderate', '{}'),
  ('mathematics', 'inverse-trigonometry', 'For x in [−1, 1], sin⁻¹x + cos⁻¹x equals:', 'π/2', 'π/4', 'π', '0', 'A', 'This is a standard identity: sin⁻¹x + cos⁻¹x = π/2.', 'Inverse trig identities', 'easy', '{}'),
  ('mathematics', 'complex-numbers', 'The value of i²⁰²⁶ is:', '1', '−1', 'i', '−i', 'B', '2026 = 4 × 506 + 2, so i²⁰²⁶ = i² = −1.', 'Powers of i', 'moderate', '{}'),
  ('mathematics', 'complex-numbers', 'The modulus of 3 + 4i is:', '7', '25', '5', '√7', 'C', '|3 + 4i| = √(9 + 16) = 5.', 'Modulus', 'easy', '{}'),
  ('mathematics', 'quadratic-equations', 'If α and β are the roots of x² − 5x + 6 = 0, then α² + β² is:', '25', '19', '12', '13', 'D', 'α + β = 5, αβ = 6; α² + β² = 25 − 12 = 13.', 'Sum and product of roots', 'moderate', '{}'),
  ('mathematics', 'permutations-combinations', 'The value of ⁸C₃ is:', '56', '70', '336', '24', 'A', '⁸C₃ = (8 × 7 × 6)/(3 × 2 × 1) = 56.', 'Combinations', 'easy', '{}'),
  ('mathematics', 'binomial-theorem', 'The number of terms in the expansion of (x + y)¹⁰ is:', '10', '11', '12', '20', 'B', '(x + y)ⁿ has n + 1 terms.', 'Binomial expansion', 'easy', '{}'),
  ('mathematics', 'binomial-theorem', 'The coefficient of the middle term in the expansion of (1 + x)⁶ is:', '35', '6', '20', '15', 'C', 'The middle term is T₄ = ⁶C₃ x³, coefficient 20.', 'Middle term', 'moderate', '{}'),
  ('mathematics', 'sequences-series', 'In an AP, the 3rd term is 8 and the 7th term is 20. The 10th term is:', '32', '26', '30', '29', 'D', '4d = 12 ⇒ d = 3, a = 2; a₁₀ = 2 + 27 = 29.', 'Arithmetic progression', 'moderate', '{}'),
  ('mathematics', 'sequences-series', 'The sum of the infinite GP 1 + 1/2 + 1/4 + … is:', '2', 'Infinite', '1', '3/2', 'A', 'S∞ = a/(1 − r) = 1/(1 − ½) = 2.', 'Infinite GP', 'easy', '{}'),
  ('mathematics', 'straight-lines', 'The slope of the line through (2, 3) and (4, 7) is:', '1/2', '2', '4', '−2', 'B', 'm = (7 − 3)/(4 − 2) = 2.', 'Slope', 'easy', '{}'),
  ('mathematics', 'straight-lines', 'The perpendicular distance of (3, 4) from the line 3x + 4y − 5 = 0 is:', '3', '5', '4', '20', 'C', '|9 + 16 − 5|/√(9 + 16) = 20/5 = 4.', 'Distance of a point from a line', 'moderate', '{}'),
  ('mathematics', 'circles', 'The centre and radius of x² + y² − 4x + 6y − 12 = 0 are:', '(−2, 3), 5', '(2, −3), 25', '(2, 3), 5', '(2, −3), 5', 'D', 'Centre (−g, −f) = (2, −3); r = √(4 + 9 + 12) = 5.', 'Equation of a circle', 'moderate', '{}'),
  ('mathematics', 'conic-sections', 'The focus of the parabola y² = 8x is:', '(2, 0)', '(8, 0)', '(4, 0)', '(0, 2)', 'A', 'y² = 4ax with a = 2 gives focus (a, 0) = (2, 0).', 'Parabola', 'easy', '{}'),
  ('mathematics', 'conic-sections', 'The eccentricity of the ellipse x²/25 + y²/16 = 1 is:', '5/3', '3/5', '4/5', '9/25', 'B', 'e = √(1 − b²/a²) = √(1 − 16/25) = 3/5.', 'Ellipse', 'exam', '{}'),
  ('mathematics', 'limits', 'lim (x → 0) sin 3x / x equals:', '0', '1/3', '3', '1', 'C', 'sin 3x / x = 3 · (sin 3x / 3x) → 3.', 'Standard limits', 'easy', '{}'),
  ('mathematics', 'limits', 'lim (x → 2) (x² − 4)/(x − 2) equals:', '0', 'Does not exist', '2', '4', 'D', 'Factor: (x − 2)(x + 2)/(x − 2) = x + 2 → 4.', 'Limits by factorisation', 'easy', '{}'),
  ('mathematics', 'continuity', 'The function f(x) = |x| at x = 0 is:', 'Continuous but not differentiable', 'Differentiable but not continuous', 'Continuous and differentiable', 'Discontinuous', 'A', '|x| is continuous at 0, but the left derivative (−1) differs from the right derivative (+1).', 'Continuity and differentiability', 'moderate', '{}'),
  ('mathematics', 'differentiation', 'd/dx (x² sin x) is:', '2x cos x', '2x sin x + x² cos x', '2x sin x − x² cos x', 'x² cos x', 'B', 'Product rule: (x²)′ sin x + x² (sin x)′.', 'Product rule', 'moderate', '{}'),
  ('mathematics', 'differentiation', 'd/dx (tan⁻¹ x) is:', 'sec² x', '−1/(1 + x²)', '1/(1 + x²)', '1/√(1 − x²)', 'C', 'Standard derivative.', 'Derivatives of inverse trig', 'easy', '{}'),
  ('mathematics', 'applications-derivatives', 'The minimum value of x² − 6x + 10 is:', '3', '10', '−1', '1', 'D', 'x² − 6x + 10 = (x − 3)² + 1, minimum 1 at x = 3.', 'Maxima and minima', 'moderate', '{}'),
  ('mathematics', 'applications-derivatives', 'The slope of the tangent to y = x³ at x = 2 is:', '12', '8', '4', '6', 'A', 'dy/dx = 3x² = 12 at x = 2.', 'Tangents', 'easy', '{}'),
  ('mathematics', 'indefinite-integration', '∫ x eˣ dx equals:', 'eˣ(x + 1) + C', 'eˣ(x − 1) + C', 'x² eˣ/2 + C', 'x eˣ + C', 'B', 'By parts: x eˣ − ∫ eˣ dx = eˣ(x − 1) + C.', 'Integration by parts', 'moderate', '{}'),
  ('mathematics', 'definite-integration', '∫₀^{π/2} sin² x dx equals:', '1/2', '1', 'π/4', 'π/2', 'C', 'Using ∫₀^a f(x) dx = ∫₀^a f(a − x) dx, the sin² and cos² integrals are equal and sum to π/2, so each is π/4.', 'Properties of definite integrals', 'exam', '{}'),
  ('mathematics', 'definite-integration', '∫₋₁¹ x³ dx equals:', '1', '1/2', '2', '0', 'D', 'x³ is an odd function, so its integral over a symmetric interval is 0.', 'Odd functions', 'easy', '{}'),
  ('mathematics', 'applications-integration', 'The area enclosed between y = x² and y = x is:', '1/6', '1/2', '1/12', '1/3', 'A', 'They meet at x = 0 and 1: ∫₀¹ (x − x²) dx = 1/2 − 1/3 = 1/6.', 'Area between curves', 'exam', '{}'),
  ('mathematics', 'differential-equations', 'The order and degree of (d²y/dx²)³ + (dy/dx)⁴ + y = 0 are:', 'Order 2, degree 4', 'Order 2, degree 3', 'Order 3, degree 2', 'Order 4, degree 2', 'B', 'Highest derivative is d²y/dx² (order 2); its power is 3 (degree 3).', 'Order and degree', 'moderate', '{}'),
  ('mathematics', 'differential-equations', 'The general solution of dy/dx = y is:', 'y = x + C', 'y = Cx', 'y = Ceˣ', 'y = eˣ + C', 'C', 'dy/y = dx ⇒ ln y = x + c ⇒ y = Ceˣ.', 'Variable separable', 'easy', '{}'),
  ('mathematics', 'differential-equations', 'The integrating factor of dy/dx + y/x = x² is:', 'log x', '1/x', 'eˣ', 'x', 'D', 'IF = e^{∫(1/x)dx} = e^{ln x} = x.', 'Linear differential equations', 'exam', '{}'),
  ('mathematics', 'determinants', 'If A is a 3 × 3 matrix with |A| = 4, then |2A| is:', '32', '16', '64', '8', 'A', '|kA| = kⁿ|A| = 2³ × 4 = 32.', 'Properties of determinants', 'moderate', '{}'),
  ('mathematics', 'determinants', 'If A is a 3 × 3 matrix with |A| = 5, then |adj A| is:', '1/5', '25', '125', '5', 'B', '|adj A| = |A|ⁿ⁻¹ = 5² = 25.', 'Adjoint', 'exam', '{}'),
  ('mathematics', 'matrices', 'For matrices A and B for which AB is defined, (AB)ᵀ equals:', 'AᵀBᵀ', 'BA', 'BᵀAᵀ', 'AB', 'C', 'The transpose of a product reverses the order: (AB)ᵀ = BᵀAᵀ.', 'Transpose', 'easy', '{}'),
  ('mathematics', 'vectors', 'If a = i + 2j + 3k and b = 2i − j + k, then a · b is:', '5', '0', '1', '3', 'D', 'a · b = 2 − 2 + 3 = 3.', 'Dot product', 'easy', '{}'),
  ('mathematics', 'vectors', 'If a and b are perpendicular unit vectors, |a × b| is:', '1', '2', '0', '√2', 'A', '|a × b| = |a||b| sin 90° = 1.', 'Cross product', 'moderate', '{}'),
  ('mathematics', '3d-geometry', 'The direction cosines of a line equally inclined to the three coordinate axes are:', '±1/3, ±1/3, ±1/3', '±1/√3, ±1/√3, ±1/√3', '±1, ±1, ±1', '±1/√2, ±1/√2, 0', 'B', 'l = m = n and l² + m² + n² = 1, so each is ±1/√3.', 'Direction cosines', 'moderate', '{}'),
  ('mathematics', '3d-geometry', 'The distance of the point (1, 2, 3) from the plane 2x − y + 2z − 3 = 0 is:', '2', '1/3', '1', '3', 'C', '|2 − 2 + 6 − 3|/√(4 + 1 + 4) = 3/3 = 1.', 'Distance from a plane', 'exam', '{}'),
  ('mathematics', 'probability', 'A and B are independent events with P(A) = 0.4 and P(B) = 0.5. P(A ∪ B) is:', '0.9', '0.2', '0.5', '0.7', 'D', 'P(A ∩ B) = 0.2, so P(A ∪ B) = 0.4 + 0.5 − 0.2 = 0.7.', 'Independent events', 'moderate', '{}'),
  ('mathematics', 'probability', 'A bag has 3 red and 2 black balls. Two balls are drawn without replacement. The probability that both are red is:', '3/10', '9/25', '1/5', '3/5', 'A', '(3/5) × (2/4) = 3/10.', 'Conditional probability', 'moderate', '{}'),
  ('mathematics', 'probability', 'Box I has 2 red and 3 blue balls; Box II has 4 red and 1 blue. A box is chosen at random and a ball drawn is red. The probability that it came from Box II is:', '4/5', '2/3', '1/2', '1/3', 'B', 'Bayes: (½ × 4/5) / (½ × 2/5 + ½ × 4/5) = 0.4/0.6 = 2/3.', 'Bayes'' theorem', 'challenging', '{}'),
  ('mathematics', 'statistics', 'The variance of 2, 4, 6, 8, 10 is:', '40', '6', '8', '√8', 'C', 'Mean 6; squared deviations 16, 4, 0, 4, 16 sum to 40; 40/5 = 8.', 'Variance', 'moderate', '{}'),
  ('management', 'scientific-management', 'Who is known as the father of Scientific Management?', 'Elton Mayo', 'Henri Fayol', 'Max Weber', 'F. W. Taylor', 'D', 'Frederick Winslow Taylor developed scientific management (time and motion study, differential piece rate).', 'Scientific management', 'easy', '{}'),
  ('management', 'fayol-principles', 'How many principles of management did Henri Fayol give?', '14', '10', '16', '12', 'A', 'Fayol gave 14 general principles of management.', 'Fayol''s principles', 'easy', '{}'),
  ('management', 'fayol-principles', '"An employee should receive orders from only one superior" is Fayol''s principle of:', 'Unity of direction', 'Unity of command', 'Scalar chain', 'Centralisation', 'B', 'Unity of command = one boss. Unity of direction = one head and one plan for a group of activities with the same objective.', 'Unity of command', 'moderate', '{}'),
  ('management', 'fayol-principles', 'Fayol''s concept of ''gang plank'' is related to the principle of:', 'Unity of command', 'Order', 'Scalar chain', 'Equity', 'C', 'The gang plank allows direct communication between same-level employees, as a shortcut in the scalar chain.', 'Scalar chain', 'exam', '{}'),
  ('management', 'bureaucracy', 'The bureaucratic model of organisation is associated with:', 'Chester Barnard', 'Abraham Maslow', 'Peter Drucker', 'Max Weber', 'D', 'Max Weber proposed bureaucracy based on rules, hierarchy and impersonality.', 'Bureaucracy', 'easy', '{}'),
  ('management', 'human-relations', 'The Hawthorne experiments, which led to the human relations approach, were conducted by:', 'Elton Mayo', 'Douglas McGregor', 'F. W. Taylor', 'Henry Gantt', 'A', 'Elton Mayo and colleagues found that social and psychological factors affect productivity.', 'Hawthorne studies', 'moderate', '{}'),
  ('management', 'maslow', 'In Maslow''s hierarchy, the highest-level need is:', 'Esteem', 'Self-actualisation', 'Social', 'Safety', 'B', 'Order: physiological → safety → social → esteem → self-actualisation.', 'Maslow''s hierarchy', 'easy', '{}'),
  ('management', 'herzberg', 'According to Herzberg, which of these is a hygiene (maintenance) factor?', 'Recognition', 'Responsibility', 'Salary', 'Achievement', 'C', 'Hygiene factors (salary, working conditions, policy) prevent dissatisfaction; motivators include achievement and recognition.', 'Two-factor theory', 'moderate', '{}'),
  ('management', 'mcgregor', 'McGregor''s Theory X assumes that the average employee:', 'Seeks responsibility', 'Is self-directed', 'Is creative and innovative', 'Dislikes work and must be controlled', 'D', 'Theory X is the traditional, pessimistic view; Theory Y assumes people like work and seek responsibility.', 'Theory X and Y', 'moderate', '{}'),
  ('management', 'theory-z', 'Theory Z, based on Japanese management practices, was given by:', 'William Ouchi', 'Douglas McGregor', 'Rensis Likert', 'Frederick Herzberg', 'A', 'William Ouchi proposed Theory Z (1981), stressing long-term employment and collective decisions.', 'Theory Z', 'moderate', '{}'),
  ('management', 'levels-roles', 'In Mintzberg''s managerial roles, ''spokesperson'' belongs to which category?', 'Decisional', 'Informational', 'Technical', 'Interpersonal', 'B', 'Informational roles: monitor, disseminator, spokesperson.', 'Mintzberg''s roles', 'exam', '{}'),
  ('management', 'planning', 'The concept of Management by Objectives (MBO) was popularised by:', 'Henri Fayol', 'Philip Kotler', 'Peter Drucker', 'Herbert Simon', 'C', 'Peter Drucker introduced MBO in The Practice of Management (1954).', 'MBO', 'moderate', '{}'),
  ('management', 'planning', 'Which is known as the primary function of management?', 'Controlling', 'Staffing', 'Organising', 'Planning', 'D', 'Planning comes first; all other functions are carried out within the framework of plans.', 'Primacy of planning', 'easy', '{}'),
  ('management', 'strategic-management', 'The concept of ''core competence'' was given by:', 'C. K. Prahalad and Gary Hamel', 'Peter Drucker', 'Igor Ansoff', 'Michael Porter', 'A', 'Prahalad and Hamel introduced core competence in 1990.', 'Core competence', 'exam', '{}'),
  ('management', 'controlling', 'The first step in the controlling process is:', 'Measuring actual performance', 'Setting performance standards', 'Taking corrective action', 'Analysing deviations', 'B', 'Standards must be set before performance can be measured and compared.', 'Controlling process', 'moderate', '{}'),
  ('management', 'organizing', 'In delegation, which of the following cannot be delegated?', 'Work', 'Duties', 'Accountability', 'Authority', 'C', 'Authority is delegated, but the manager remains accountable for the result.', 'Delegation', 'exam', '{}'),
  ('management', 'organizing', '''Span of control'' refers to:', 'The duration of a manager''s tenure', 'The area of a manager''s authority', 'The number of levels in an organisation', 'The number of subordinates a manager can supervise effectively', 'D', 'Span of management is the number of subordinates reporting to one manager.', 'Span of control', 'moderate', '{}'),
  ('management', 'communication', '''Grapevine'' refers to:', 'Informal communication', 'Formal written communication', 'Mass communication', 'Downward communication', 'A', 'Grapevine is the informal network through which information spreads.', 'Informal communication', 'easy', '{}'),
  ('management', 'leadership-styles', 'Free-rein leadership is also called:', 'Democratic', 'Laissez-faire', 'Paternalistic', 'Autocratic', 'B', 'Under laissez-faire leadership the group is given freedom to decide.', 'Leadership styles', 'easy', '{}'),
  ('management', 'situational-leadership', 'The situational leadership model is associated with:', 'Taylor and Gilbreth', 'Maslow and Alderfer', 'Hersey and Blanchard', 'Blake and Mouton', 'C', 'Hersey and Blanchard linked leadership style to follower readiness.', 'Situational leadership', 'moderate', '{}'),
  ('management', 'trait-theory', 'The trait theory of leadership assumes that:', 'Leaders are made through training', 'Leadership depends on the situation', 'Leadership depends on followers only', 'Leaders possess certain inborn qualities', 'D', 'Trait theory holds that leaders are born with qualities such as intelligence and self-confidence.', 'Trait theory', 'moderate', '{}'),
  ('management', 'selection', 'Which HR process is described as a ''negative'' process?', 'Selection', 'Training', 'Recruitment', 'Induction', 'A', 'Recruitment attracts applicants (positive); selection rejects unsuitable ones (negative).', 'Recruitment vs selection', 'moderate', '{}'),
  ('management', 'training', 'Training given in a setting that replicates the actual workplace, away from the shop floor, is called:', 'Apprenticeship', 'Vestibule training', 'Coaching', 'Job rotation', 'B', 'Vestibule training uses a replica of the work environment; the others are on-the-job methods.', 'Training methods', 'exam', '{}'),
  ('management', 'performance-appraisal', 'In 360-degree appraisal, feedback is collected from:', 'Only the immediate supervisor', 'Supervisors, peers, subordinates and others', 'Only the HR department', 'Only customers', 'B', '360-degree feedback gathers views from all around the employee.', 'Performance appraisal', 'moderate', '{}'),
  ('management', 'marketing-mix', 'The 4 Ps classification of the marketing mix was popularised by:', 'Neil Borden', 'Philip Kotler', 'Theodore Levitt', 'E. Jerome McCarthy', 'D', 'McCarthy grouped the marketing mix into Product, Price, Place and Promotion (1960).', 'Marketing mix', 'moderate', '{}'),
  ('management', 'promotion', 'Which of the following is NOT an element of the promotion mix?', 'Packaging', 'Personal selling', 'Advertising', 'Sales promotion', 'A', 'Promotion mix = advertising, personal selling, sales promotion and public relations. Packaging is part of product.', 'Promotion mix', 'easy', '{}'),
  ('management', 'branding', 'A brand, or part of a brand, that is given legal protection is called a:', 'Label', 'Trademark', 'Logo', 'Brand mark', 'B', 'A registered trademark has exclusive legal protection.', 'Branding', 'moderate', '{}'),
  ('management', 'directing', 'Which of the following is NOT an element of directing?', 'Supervision', 'Motivation', 'Staffing', 'Leadership', 'C', 'Directing = supervision, motivation, leadership and communication. Staffing is a separate function.', 'Directing', 'easy', '{}'),
  ('management', 'coordination', 'Which is regarded as the ''essence of management''?', 'Planning', 'Staffing', 'Controlling', 'Coordination', 'D', 'Coordination integrates all functions and runs through the whole management process.', 'Coordination', 'moderate', '{}'),
  ('management', 'decision-making', 'The concept of ''bounded rationality'' in decision making was given by:', 'Herbert Simon', 'Chester Barnard', 'Peter Drucker', 'Henri Fayol', 'A', 'Herbert Simon argued that decision makers ''satisfice'' because of limited information and capacity.', 'Bounded rationality', 'exam', '{}'),
  ('management', 'mis', 'The main purpose of a Management Information System (MIS) is to:', 'Record only financial transactions', 'Provide timely, relevant information for decision making', 'Replace managers', 'Train employees', 'B', 'MIS gives managers the information they need for planning, control and decisions.', 'MIS', 'moderate', '{}')
) as v(subj, topic, q, a, b, c, d, ans, expl, concept, diff, tags)
join subjects s on s.slug = v.subj join topics t on t.subject_id = s.id and t.slug = v.topic;

insert into revision_notes (subject_id, category, title, body, sort_order)
select s.id, v.cat, v.title, v.body, v.ord from (values
  ('physics', 'formula', 'Mechanics', 'Equations of motion :: v = u + at ; s = ut + ½at² ; v² = u² + 2as
Projectile range :: R = u² sin2θ / g (max at 45°)
Max height :: H = u² sin²θ / 2g
Newton''s second law :: F = ma = dp/dt
Impulse :: J = FΔt = Δp
Work :: W = F·s·cosθ
Kinetic energy :: KE = ½mv² = p²/2m
Power :: P = W/t = F·v
Centripetal force :: F = mv²/r
Moment of inertia :: ring MR² ; disc ½MR² ; solid sphere ⅖MR² ; rod (centre) ML²/12
Angular momentum :: L = Iω (conserved when no external torque)
Gravitation :: F = Gm₁m₂/r² ; g = GM/R²
g at height h :: g'' = g(1 − 2h/R) for h ≪ R ; g'' = gR²/(R + h)²
Escape velocity :: vₑ = √(2gR) ≈ 11.2 km/s
Orbital velocity :: v₀ = √(gR) ≈ 7.9 km/s', 1),
  ('physics', 'formula', 'Fluids, Heat & Oscillations', 'Hydrostatic pressure :: P = ρgh
Bernoulli :: P + ½ρv² + ρgh = constant
Young''s modulus :: Y = (F/A)/(ΔL/L)
First law of thermodynamics :: ΔQ = ΔU + ΔW
Isothermal (ideal gas) :: ΔU = 0 ; W = nRT ln(V₂/V₁)
Adiabatic :: PV^γ = constant ; Q = 0
Carnot efficiency :: η = 1 − T₂/T₁
RMS speed :: v_rms = √(3RT/M)
Simple pendulum :: T = 2π√(l/g)
Spring–mass :: T = 2π√(m/k)
Wave speed :: v = fλ', 2),
  ('physics', 'formula', 'Electricity & Magnetism', 'Coulomb''s law :: F = kq₁q₂/r², k = 9 × 10⁹ N m²/C²
Gauss''s law :: Φ = q/ε₀
Capacitance (parallel plate) :: C = ε₀A/d
Capacitors :: series 1/C = Σ1/Cᵢ ; parallel C = ΣCᵢ
Energy in capacitor :: U = ½CV²
Ohm''s law :: V = IR
Resistors :: series R = ΣRᵢ ; parallel 1/R = Σ1/Rᵢ
Electric power :: P = VI = I²R = V²/R
Field at centre of loop :: B = μ₀I/2R
Field of long straight wire :: B = μ₀I/2πr
Solenoid :: B = μ₀nI
Lorentz force :: F = qvB sinθ
Faraday''s law :: e = −dΦ/dt
AC :: V_rms = V₀/√2 ; resonance f = 1/(2π√LC) ; power factor cosφ = R/Z
Transformer :: Vs/Vp = Ns/Np', 3),
  ('physics', 'formula', 'Optics & Modern Physics', 'Mirror formula :: 1/v + 1/u = 1/f ; f = R/2
Lens formula :: 1/v − 1/u = 1/f
Power of lens :: P = 1/f (f in metres), unit dioptre
Refractive index :: n = c/v
Snell''s law :: n₁ sinθ₁ = n₂ sinθ₂
YDSE fringe width :: β = λD/d
Photon energy :: E = hν = hc/λ
Photoelectric equation :: K_max = hν − φ
de Broglie :: λ = h/p ; electron: λ = 1.227/√V nm
Bohr energy (H) :: Eₙ = −13.6/n² eV
Radioactive decay :: N = N₀(½)^(t/T½)
Mass–energy :: E = mc² ; 1 u = 931.5 MeV
Constants :: c = 3×10⁸ m/s ; h = 6.63×10⁻³⁴ J s ; e = 1.6×10⁻¹⁹ C', 4),
  ('mathematics', 'formula', 'Algebra & Trigonometry', 'Quadratic roots :: x = [−b ± √(b² − 4ac)]/2a ; α+β = −b/a ; αβ = c/a
AP :: aₙ = a + (n−1)d ; Sₙ = n/2 [2a + (n−1)d]
GP :: aₙ = arⁿ⁻¹ ; S∞ = a/(1 − r), |r| < 1
Binomial :: T(r+1) = ⁿCᵣ aⁿ⁻ʳ bʳ ; (n + 1) terms
Combinations :: ⁿCᵣ = n!/[r!(n−r)!] ; ⁿPᵣ = n!/(n−r)!
Complex :: |a + ib| = √(a² + b²) ; i⁴ = 1
Identities :: sin²θ + cos²θ = 1 ; 1 + tan²θ = sec²θ
Compound angles :: sin(A±B) = sinA cosB ± cosA sinB
Double angle :: sin2A = 2 sinA cosA ; cos2A = 1 − 2sin²A
a sinx + b cosx :: range [−√(a²+b²), √(a²+b²)]
Inverse trig :: sin⁻¹x + cos⁻¹x = π/2 ; tan⁻¹x + cot⁻¹x = π/2
Determinants :: |kA| = kⁿ|A| ; |adj A| = |A|ⁿ⁻¹ ; A⁻¹ = adj A / |A|', 5),
  ('mathematics', 'formula', 'Calculus', 'Standard limit :: lim sinx/x = 1 (x→0) ; lim (eˣ − 1)/x = 1
Derivatives :: d(xⁿ) = nxⁿ⁻¹ ; d(sinx) = cosx ; d(eˣ) = eˣ ; d(ln x) = 1/x
Inverse trig derivatives :: d(tan⁻¹x) = 1/(1+x²) ; d(sin⁻¹x) = 1/√(1−x²)
Product / quotient :: (uv)′ = u′v + uv′ ; (u/v)′ = (u′v − uv′)/v²
Integration by parts :: ∫u dv = uv − ∫v du
Standard integrals :: ∫1/x dx = ln|x| ; ∫eˣ dx = eˣ ; ∫1/(1+x²) dx = tan⁻¹x
Definite property :: ∫₀ᵃ f(x)dx = ∫₀ᵃ f(a − x)dx
Odd/even :: ∫₋ₐᵃ odd = 0 ; ∫₋ₐᵃ even = 2∫₀ᵃ
Area between curves :: ∫ₐᵇ [f(x) − g(x)] dx
Linear DE :: dy/dx + Py = Q → IF = e^(∫P dx)', 6),
  ('mathematics', 'formula', 'Coordinate Geometry, Vectors & Probability', 'Slope :: m = (y₂ − y₁)/(x₂ − x₁)
Point–line distance :: |ax₁ + by₁ + c|/√(a² + b²)
Circle :: x² + y² + 2gx + 2fy + c = 0 → centre (−g, −f), r = √(g² + f² − c)
Parabola y² = 4ax :: focus (a, 0), directrix x = −a
Ellipse :: e = √(1 − b²/a²)
Hyperbola :: e = √(1 + b²/a²)
Dot product :: a·b = |a||b|cosθ
Cross product :: |a×b| = |a||b|sinθ
Point–plane distance :: |ax₁ + by₁ + cz₁ + d|/√(a² + b² + c²)
Probability :: P(A∪B) = P(A) + P(B) − P(A∩B)
Independent :: P(A∩B) = P(A)P(B)
Bayes :: P(Eᵢ|A) = P(Eᵢ)P(A|Eᵢ) / ΣP(Eⱼ)P(A|Eⱼ)
Variance :: σ² = Σ(x − x̄)²/n', 7),
  ('quant', 'formula', 'Arithmetic Shortcuts', 'Percentage change :: (new − old)/old × 100
Successive change :: a + b + ab/100
Profit % :: (SP − CP)/CP × 100
Discount :: SP = MP × (1 − d/100)
Simple interest :: SI = PRT/100
Compound interest :: A = P(1 + R/100)ᵀ
Ratio share :: part = (its ratio / sum of ratios) × total
Average :: sum / count
Time & work :: A and B together = ab/(a + b) days
Pipes :: net rate = fill rate − empty rate
Speed :: km/h × 5/18 = m/s
Train crossing :: time = (train length + object length)/relative speed
Boats :: stream = (down − up)/2 ; boat = (down + up)/2
Alligation :: cheaper : dearer = (dearer − mean) : (mean − cheaper)
Partnership :: profit ∝ capital × time', 8),
  ('ga-aviation', 'aviation_fact', 'Organisations', 'ICAO :: UN agency, HQ Montreal; created by the Chicago Convention, 7 Dec 1944
IATA :: Trade association of airlines, founded 1945 in Havana
ACI :: Airports Council International — association of airport operators
DGCA :: India''s civil aviation regulator (safety, licensing, airworthiness)
BCAS :: Regulator for civil aviation security in India
AAI :: Formed 1 April 1995 under the AAI Act 1994; manages airports and air navigation services
AERA :: Sets tariffs for aeronautical services at major airports (AERA Act 2008)
CISF :: Provides security at many Indian airports
MoCA :: Ministry of Civil Aviation — parent ministry of DGCA, BCAS, AAI', 9),
  ('ga-aviation', 'aviation_fact', 'Airport Codes & Airports', 'DEL :: Delhi — Indira Gandhi International (ICAO VIDP)
BOM :: Mumbai — Chhatrapati Shivaji Maharaj International (VABB)
MAA :: Chennai International (VOMM)
CCU :: Kolkata — Netaji Subhas Chandra Bose International (VECC)
BLR :: Bengaluru — Kempegowda International
HYD :: Hyderabad — Rajiv Gandhi International
COK :: Kochi — Cochin International (first fully solar-powered airport)
AMD :: Ahmedabad — Sardar Vallabhbhai Patel International
GAU :: Guwahati — Lokpriya Gopinath Bordoloi International
LKO :: Lucknow — Chaudhary Charan Singh International
ICAO prefix :: Indian ICAO location indicators start with V', 10),
  ('ga-aviation', 'aviation_fact', 'Abbreviations & ATC', 'ATC :: Air Traffic Control
CNS/ATM :: Communication, Navigation, Surveillance / Air Traffic Management
ILS :: Instrument Landing System — localizer (lateral) + glide slope (vertical)
VOR :: VHF Omnidirectional Range
DME :: Distance Measuring Equipment
NDB :: Non-Directional Beacon
METAR :: Routine aerodrome weather report
TAF :: Terminal Aerodrome Forecast
NOTAM :: Notice to Airmen
ETA / ETD :: Estimated Time of Arrival / Departure
Squawk codes :: 7500 hijack ; 7600 radio failure ; 7700 emergency
ICAO Annexes :: 9 Facilitation ; 14 Aerodromes ; 17 Security ; 19 Safety Management', 11),
  ('ga-aviation', 'aviation_fact', 'Airport Processes & Areas', 'Passenger flow :: Check-in → security screening → (immigration) → boarding gate → aircraft
Airside / landside :: Airside is beyond security screening; landside is open to the public
Apron :: Area for parking, loading, refuelling and boarding
Taxiway :: Path linking runways with aprons and hangars
Runway numbering :: Magnetic heading ÷ 10; opposite ends differ by 18 (09/27)
Aerobridge :: Passenger boarding bridge from gate to aircraft door
Customs :: Green Channel = nothing to declare ; Red Channel = goods to declare
Baggage :: Hold (checked) baggage in the cargo hold ; cabin baggage with the passenger
Four forces of flight :: Lift ↔ weight ; thrust ↔ drag
Flight recorders :: CVR + FDR, painted bright orange
UDAN :: Regional Connectivity Scheme under the National Civil Aviation Policy 2016', 12)
) as v(subj, cat, title, body, ord) join subjects s on s.slug = v.subj;

insert into tests (kind, title, series_label, series_number, description, config, is_published) values
  ('full_mock', 'Mock 01 — Foundation', 'Foundation', 1, 'Foundation difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":3,"moderate":2,"exam":1,"challenging":0.2}}', true),
  ('full_mock', 'Mock 02 — Foundation', 'Foundation', 2, 'Foundation difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":3,"moderate":2,"exam":1,"challenging":0.2}}', true),
  ('full_mock', 'Mock 03 — Standard', 'Standard', 3, 'Standard difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":1,"moderate":3,"exam":2,"challenging":0.5}}', true),
  ('full_mock', 'Mock 04 — Standard', 'Standard', 4, 'Standard difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":1,"moderate":3,"exam":2,"challenging":0.5}}', true),
  ('full_mock', 'Mock 05 — Standard', 'Standard', 5, 'Standard difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":1,"moderate":3,"exam":2,"challenging":0.5}}', true),
  ('full_mock', 'Mock 06 — Exam Level', 'Exam Level', 6, 'Exam Level difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":0.5,"moderate":1.5,"exam":3,"challenging":1}}', true),
  ('full_mock', 'Mock 07 — Exam Level', 'Exam Level', 7, 'Exam Level difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":0.5,"moderate":1.5,"exam":3,"challenging":1}}', true),
  ('full_mock', 'Mock 08 — Advanced Practice', 'Advanced Practice', 8, 'Advanced Practice difficulty. 120 questions in the exact exam distribution, drawn fresh from the question bank.', '{"weights":{"easy":0.2,"moderate":1,"exam":2,"challenging":3}}', true),
  ('exam_simulation', 'Mock 09 — Exam Simulation', 'Exam Simulation', 9, 'Strict exam conditions: 120 questions, 120 minutes, no explanations until you submit, auto-submit at 00:00.', '{"weights":{"easy":1,"moderate":2,"exam":3,"challenging":1}}', true),
  ('exam_simulation', 'Mock 10 — Final Simulation', 'Final Simulation', 10, 'Strict exam conditions: 120 questions, 120 minutes, no explanations until you submit, auto-submit at 00:00.', '{"weights":{"easy":1,"moderate":2,"exam":3,"challenging":1}}', true);
